// Code generated by Kitex v0.16.3. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "github.com/kouleen/idl/kitex_gen/user"
	user_position "github.com/kouleen/idl/kitex_gen/user_position"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Captcha": kitex.NewMethodInfo(
		captchaHandler,
		newUserServiceCaptchaArgs,
		newUserServiceCaptchaResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SmsCode": kitex.NewMethodInfo(
		smsCodeHandler,
		newUserServiceSmsCodeArgs,
		newUserServiceSmsCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResetPwd": kitex.NewMethodInfo(
		resetPwdHandler,
		newUserServiceResetPwdArgs,
		newUserServiceResetPwdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newUserServiceLogoutArgs,
		newUserServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserHeaderPage": kitex.NewMethodInfo(
		queryUserHeaderPageHandler,
		newUserServiceQueryUserHeaderPageArgs,
		newUserServiceQueryUserHeaderPageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserHeaderList": kitex.NewMethodInfo(
		queryUserHeaderListHandler,
		newUserServiceQueryUserHeaderListArgs,
		newUserServiceQueryUserHeaderListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserHeaderInfo": kitex.NewMethodInfo(
		queryUserHeaderInfoHandler,
		newUserServiceQueryUserHeaderInfoArgs,
		newUserServiceQueryUserHeaderInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryUserPositionPage": kitex.NewMethodInfo(
		queryUserPositionPageHandler,
		newUserServiceQueryUserPositionPageArgs,
		newUserServiceQueryUserPositionPageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SaveUserPosition": kitex.NewMethodInfo(
		saveUserPositionHandler,
		newUserServiceSaveUserPositionArgs,
		newUserServiceSaveUserPositionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserPosition": kitex.NewMethodInfo(
		updateUserPositionHandler,
		newUserServiceUpdateUserPositionArgs,
		newUserServiceUpdateUserPositionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUserPosition": kitex.NewMethodInfo(
		deleteUserPositionHandler,
		newUserServiceDeleteUserPositionArgs,
		newUserServiceDeleteUserPositionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func captchaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCaptchaArgs)
	realResult := result.(*user.UserServiceCaptchaResult)
	success, err := handler.(user.UserService).Captcha(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCaptchaArgs() interface{} {
	return user.NewUserServiceCaptchaArgs()
}

func newUserServiceCaptchaResult() interface{} {
	return user.NewUserServiceCaptchaResult()
}

func smsCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSmsCodeArgs)
	realResult := result.(*user.UserServiceSmsCodeResult)
	success, err := handler.(user.UserService).SmsCode(ctx, realArg.Phone)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceSmsCodeArgs() interface{} {
	return user.NewUserServiceSmsCodeArgs()
}

func newUserServiceSmsCodeResult() interface{} {
	return user.NewUserServiceSmsCodeResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func resetPwdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceResetPwdArgs)
	realResult := result.(*user.UserServiceResetPwdResult)
	success, err := handler.(user.UserService).ResetPwd(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceResetPwdArgs() interface{} {
	return user.NewUserServiceResetPwdArgs()
}

func newUserServiceResetPwdResult() interface{} {
	return user.NewUserServiceResetPwdResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLogoutArgs)
	realResult := result.(*user.UserServiceLogoutResult)
	success, err := handler.(user.UserService).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceLogoutArgs() interface{} {
	return user.NewUserServiceLogoutArgs()
}

func newUserServiceLogoutResult() interface{} {
	return user.NewUserServiceLogoutResult()
}

func queryUserHeaderPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceQueryUserHeaderPageArgs)
	realResult := result.(*user.UserServiceQueryUserHeaderPageResult)
	success, err := handler.(user.UserService).QueryUserHeaderPage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceQueryUserHeaderPageArgs() interface{} {
	return user.NewUserServiceQueryUserHeaderPageArgs()
}

func newUserServiceQueryUserHeaderPageResult() interface{} {
	return user.NewUserServiceQueryUserHeaderPageResult()
}

func queryUserHeaderListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceQueryUserHeaderListArgs)
	realResult := result.(*user.UserServiceQueryUserHeaderListResult)
	success, err := handler.(user.UserService).QueryUserHeaderList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceQueryUserHeaderListArgs() interface{} {
	return user.NewUserServiceQueryUserHeaderListArgs()
}

func newUserServiceQueryUserHeaderListResult() interface{} {
	return user.NewUserServiceQueryUserHeaderListResult()
}

func queryUserHeaderInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceQueryUserHeaderInfoArgs)
	realResult := result.(*user.UserServiceQueryUserHeaderInfoResult)
	success, err := handler.(user.UserService).QueryUserHeaderInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceQueryUserHeaderInfoArgs() interface{} {
	return user.NewUserServiceQueryUserHeaderInfoArgs()
}

func newUserServiceQueryUserHeaderInfoResult() interface{} {
	return user.NewUserServiceQueryUserHeaderInfoResult()
}

func queryUserPositionPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceQueryUserPositionPageArgs)
	realResult := result.(*user.UserServiceQueryUserPositionPageResult)
	success, err := handler.(user.UserService).QueryUserPositionPage(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceQueryUserPositionPageArgs() interface{} {
	return user.NewUserServiceQueryUserPositionPageArgs()
}

func newUserServiceQueryUserPositionPageResult() interface{} {
	return user.NewUserServiceQueryUserPositionPageResult()
}

func saveUserPositionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceSaveUserPositionArgs)
	realResult := result.(*user.UserServiceSaveUserPositionResult)
	success, err := handler.(user.UserService).SaveUserPosition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceSaveUserPositionArgs() interface{} {
	return user.NewUserServiceSaveUserPositionArgs()
}

func newUserServiceSaveUserPositionResult() interface{} {
	return user.NewUserServiceSaveUserPositionResult()
}

func updateUserPositionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateUserPositionArgs)
	realResult := result.(*user.UserServiceUpdateUserPositionResult)
	success, err := handler.(user.UserService).UpdateUserPosition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceUpdateUserPositionArgs() interface{} {
	return user.NewUserServiceUpdateUserPositionArgs()
}

func newUserServiceUpdateUserPositionResult() interface{} {
	return user.NewUserServiceUpdateUserPositionResult()
}

func deleteUserPositionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceDeleteUserPositionArgs)
	realResult := result.(*user.UserServiceDeleteUserPositionResult)
	success, err := handler.(user.UserService).DeleteUserPosition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newUserServiceDeleteUserPositionArgs() interface{} {
	return user.NewUserServiceDeleteUserPositionArgs()
}

func newUserServiceDeleteUserPositionResult() interface{} {
	return user.NewUserServiceDeleteUserPositionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Captcha(ctx context.Context, req *user.LoginRequest) (r *user.CaptchaResponse, err error) {
	var _args user.UserServiceCaptchaArgs
	_args.Req = req
	var _result user.UserServiceCaptchaResult
	if err = p.c.Call(ctx, "Captcha", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SmsCode(ctx context.Context, phone string) (r bool, err error) {
	var _args user.UserServiceSmsCodeArgs
	_args.Phone = phone
	var _result user.UserServiceSmsCodeResult
	if err = p.c.Call(ctx, "SmsCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginRequest) (r *user.LoginResponse, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterRequest) (r bool, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ResetPwd(ctx context.Context, req *user.LoginRequest) (r bool, err error) {
	var _args user.UserServiceResetPwdArgs
	_args.Req = req
	var _result user.UserServiceResetPwdResult
	if err = p.c.Call(ctx, "ResetPwd", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *user.LoginRequest) (r bool, err error) {
	var _args user.UserServiceLogoutArgs
	_args.Req = req
	var _result user.UserServiceLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserHeaderPage(ctx context.Context, req *user.UserHeaderRequest) (r *user.UserHeaderPageResponse, err error) {
	var _args user.UserServiceQueryUserHeaderPageArgs
	_args.Req = req
	var _result user.UserServiceQueryUserHeaderPageResult
	if err = p.c.Call(ctx, "QueryUserHeaderPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserHeaderList(ctx context.Context, req *user.UserHeaderRequest) (r []*user.UserHeaderResponse, err error) {
	var _args user.UserServiceQueryUserHeaderListArgs
	_args.Req = req
	var _result user.UserServiceQueryUserHeaderListResult
	if err = p.c.Call(ctx, "QueryUserHeaderList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserHeaderInfo(ctx context.Context, req *user.UserHeaderRequest) (r *user.UserHeaderResponse, err error) {
	var _args user.UserServiceQueryUserHeaderInfoArgs
	_args.Req = req
	var _result user.UserServiceQueryUserHeaderInfoResult
	if err = p.c.Call(ctx, "QueryUserHeaderInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryUserPositionPage(ctx context.Context, req *user_position.UserPositionRequest) (r *user_position.UserPositionPageResponse, err error) {
	var _args user.UserServiceQueryUserPositionPageArgs
	_args.Req = req
	var _result user.UserServiceQueryUserPositionPageResult
	if err = p.c.Call(ctx, "QueryUserPositionPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SaveUserPosition(ctx context.Context, req *user_position.UserPositionRequest) (r bool, err error) {
	var _args user.UserServiceSaveUserPositionArgs
	_args.Req = req
	var _result user.UserServiceSaveUserPositionResult
	if err = p.c.Call(ctx, "SaveUserPosition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserPosition(ctx context.Context, req *user_position.UserPositionRequest) (r bool, err error) {
	var _args user.UserServiceUpdateUserPositionArgs
	_args.Req = req
	var _result user.UserServiceUpdateUserPositionResult
	if err = p.c.Call(ctx, "UpdateUserPosition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUserPosition(ctx context.Context, req *user_position.UserPositionRequest) (r bool, err error) {
	var _args user.UserServiceDeleteUserPositionArgs
	_args.Req = req
	var _result user.UserServiceDeleteUserPositionResult
	if err = p.c.Call(ctx, "DeleteUserPosition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
