// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
	"github.com/kouleen/idl/kitex_gen/common"
)

type SystemRoleRequest struct {
	RoleName    string              `thrift:"roleName,1" frugal:"1,default,string" json:"roleName"`
	RoleSort    *int32              `thrift:"roleSort,2,optional" frugal:"2,optional,i32" json:"roleSort,omitempty"`
	Status      *common.BaseStatus  `thrift:"status,3,optional" frugal:"3,optional,BaseStatus" json:"status,omitempty"`
	IdList      []int64             `thrift:"idList,4" frugal:"4,default,list<i64>" json:"idList"`
	PageRequest *common.PageRequest `thrift:"PageRequest,5" frugal:"5,default,common.PageRequest" json:"PageRequest"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255" frugal:"255,default,common.BaseRequest" json:"BaseRequest"`
}

func NewSystemRoleRequest() *SystemRoleRequest {
	return &SystemRoleRequest{}
}

func (p *SystemRoleRequest) InitDefault() {
}

func (p *SystemRoleRequest) GetRoleName() (v string) {
	return p.RoleName
}

var SystemRoleRequest_RoleSort_DEFAULT int32

func (p *SystemRoleRequest) GetRoleSort() (v int32) {
	if !p.IsSetRoleSort() {
		return SystemRoleRequest_RoleSort_DEFAULT
	}
	return *p.RoleSort
}

var SystemRoleRequest_Status_DEFAULT common.BaseStatus

func (p *SystemRoleRequest) GetStatus() (v common.BaseStatus) {
	if !p.IsSetStatus() {
		return SystemRoleRequest_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemRoleRequest) GetIdList() (v []int64) {
	return p.IdList
}

var SystemRoleRequest_PageRequest_DEFAULT *common.PageRequest

func (p *SystemRoleRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return SystemRoleRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var SystemRoleRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *SystemRoleRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return SystemRoleRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *SystemRoleRequest) SetRoleName(val string) {
	p.RoleName = val
}
func (p *SystemRoleRequest) SetRoleSort(val *int32) {
	p.RoleSort = val
}
func (p *SystemRoleRequest) SetStatus(val *common.BaseStatus) {
	p.Status = val
}
func (p *SystemRoleRequest) SetIdList(val []int64) {
	p.IdList = val
}
func (p *SystemRoleRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *SystemRoleRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *SystemRoleRequest) IsSetRoleSort() bool {
	return p.RoleSort != nil
}

func (p *SystemRoleRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemRoleRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *SystemRoleRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *SystemRoleRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleRequest(%+v)", *p)
}

var fieldIDToName_SystemRoleRequest = map[int16]string{
	1:   "roleName",
	2:   "roleSort",
	3:   "status",
	4:   "idList",
	5:   "PageRequest",
	255: "BaseRequest",
}

type SystemRoleResponse struct {
	RoleName     string               `thrift:"roleName,1" frugal:"1,default,string" json:"roleName"`
	RoleSort     int32                `thrift:"roleSort,2" frugal:"2,default,i32" json:"roleSort"`
	Status       common.BaseStatus    `thrift:"status,3" frugal:"3,default,BaseStatus" json:"status"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewSystemRoleResponse() *SystemRoleResponse {
	return &SystemRoleResponse{}
}

func (p *SystemRoleResponse) InitDefault() {
}

func (p *SystemRoleResponse) GetRoleName() (v string) {
	return p.RoleName
}

func (p *SystemRoleResponse) GetRoleSort() (v int32) {
	return p.RoleSort
}

func (p *SystemRoleResponse) GetStatus() (v common.BaseStatus) {
	return p.Status
}

var SystemRoleResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *SystemRoleResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return SystemRoleResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *SystemRoleResponse) SetRoleName(val string) {
	p.RoleName = val
}
func (p *SystemRoleResponse) SetRoleSort(val int32) {
	p.RoleSort = val
}
func (p *SystemRoleResponse) SetStatus(val common.BaseStatus) {
	p.Status = val
}
func (p *SystemRoleResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *SystemRoleResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *SystemRoleResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleResponse(%+v)", *p)
}

var fieldIDToName_SystemRoleResponse = map[int16]string{
	1:   "roleName",
	2:   "roleSort",
	3:   "status",
	255: "BaseResponse",
}

type SystemRolePageResponse struct {
	Total   int64                 `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemRoleResponse `thrift:"records,2" frugal:"2,default,list<SystemRoleResponse>" json:"records"`
}

func NewSystemRolePageResponse() *SystemRolePageResponse {
	return &SystemRolePageResponse{}
}

func (p *SystemRolePageResponse) InitDefault() {
}

func (p *SystemRolePageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemRolePageResponse) GetRecords() (v []*SystemRoleResponse) {
	return p.Records
}
func (p *SystemRolePageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemRolePageResponse) SetRecords(val []*SystemRoleResponse) {
	p.Records = val
}

func (p *SystemRolePageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRolePageResponse(%+v)", *p)
}

var fieldIDToName_SystemRolePageResponse = map[int16]string{
	1: "total",
	2: "records",
}
