// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
)

type SystemRoleUserRequest struct {
	Current    int64   `thrift:"current,1,optional" frugal:"1,optional,i64" json:"current,omitempty"`
	Size       int64   `thrift:"size,2,optional" frugal:"2,optional,i64" json:"size,omitempty"`
	Id         *int64  `thrift:"id,3,optional" frugal:"3,optional,i64" json:"id,omitempty"`
	RoleId     *int64  `thrift:"roleId,4,optional" frugal:"4,optional,i64" json:"roleId,omitempty"`
	UserIdList []int64 `thrift:"userIdList,5" frugal:"5,default,list<i64>" json:"userIdList"`
	Username   string  `thrift:"username,6" frugal:"6,default,string" json:"username"`
	Nickname   string  `thrift:"nickname,7" frugal:"7,default,string" json:"nickname"`
	Phone      string  `thrift:"phone,8" frugal:"8,default,string" json:"phone"`
	Remark     string  `thrift:"remark,9" frugal:"9,default,string" json:"remark"`
	IsDelete   *int8   `thrift:"isDelete,10,optional" frugal:"10,optional,i8" json:"isDelete,omitempty"`
	CreatedBy  *int64  `thrift:"createdBy,11,optional" frugal:"11,optional,i64" json:"createdBy,omitempty"`
	UpdatedBy  *int64  `thrift:"updatedBy,12,optional" frugal:"12,optional,i64" json:"updatedBy,omitempty"`
	CreateTime *int64  `thrift:"createTime,13,optional" frugal:"13,optional,i64" json:"createTime,omitempty"`
	UpdateTime *int64  `thrift:"updateTime,14,optional" frugal:"14,optional,i64" json:"updateTime,omitempty"`
}

func NewSystemRoleUserRequest() *SystemRoleUserRequest {
	return &SystemRoleUserRequest{
		Current: 1,
		Size:    10,
	}
}

func (p *SystemRoleUserRequest) InitDefault() {
	p.Current = 1
	p.Size = 10
}

var SystemRoleUserRequest_Current_DEFAULT int64 = 1

func (p *SystemRoleUserRequest) GetCurrent() (v int64) {
	if !p.IsSetCurrent() {
		return SystemRoleUserRequest_Current_DEFAULT
	}
	return p.Current
}

var SystemRoleUserRequest_Size_DEFAULT int64 = 10

func (p *SystemRoleUserRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return SystemRoleUserRequest_Size_DEFAULT
	}
	return p.Size
}

var SystemRoleUserRequest_Id_DEFAULT int64

func (p *SystemRoleUserRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return SystemRoleUserRequest_Id_DEFAULT
	}
	return *p.Id
}

var SystemRoleUserRequest_RoleId_DEFAULT int64

func (p *SystemRoleUserRequest) GetRoleId() (v int64) {
	if !p.IsSetRoleId() {
		return SystemRoleUserRequest_RoleId_DEFAULT
	}
	return *p.RoleId
}

func (p *SystemRoleUserRequest) GetUserIdList() (v []int64) {
	return p.UserIdList
}

func (p *SystemRoleUserRequest) GetUsername() (v string) {
	return p.Username
}

func (p *SystemRoleUserRequest) GetNickname() (v string) {
	return p.Nickname
}

func (p *SystemRoleUserRequest) GetPhone() (v string) {
	return p.Phone
}

func (p *SystemRoleUserRequest) GetRemark() (v string) {
	return p.Remark
}

var SystemRoleUserRequest_IsDelete_DEFAULT int8

func (p *SystemRoleUserRequest) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return SystemRoleUserRequest_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

var SystemRoleUserRequest_CreatedBy_DEFAULT int64

func (p *SystemRoleUserRequest) GetCreatedBy() (v int64) {
	if !p.IsSetCreatedBy() {
		return SystemRoleUserRequest_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var SystemRoleUserRequest_UpdatedBy_DEFAULT int64

func (p *SystemRoleUserRequest) GetUpdatedBy() (v int64) {
	if !p.IsSetUpdatedBy() {
		return SystemRoleUserRequest_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var SystemRoleUserRequest_CreateTime_DEFAULT int64

func (p *SystemRoleUserRequest) GetCreateTime() (v int64) {
	if !p.IsSetCreateTime() {
		return SystemRoleUserRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var SystemRoleUserRequest_UpdateTime_DEFAULT int64

func (p *SystemRoleUserRequest) GetUpdateTime() (v int64) {
	if !p.IsSetUpdateTime() {
		return SystemRoleUserRequest_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}
func (p *SystemRoleUserRequest) SetCurrent(val int64) {
	p.Current = val
}
func (p *SystemRoleUserRequest) SetSize(val int64) {
	p.Size = val
}
func (p *SystemRoleUserRequest) SetId(val *int64) {
	p.Id = val
}
func (p *SystemRoleUserRequest) SetRoleId(val *int64) {
	p.RoleId = val
}
func (p *SystemRoleUserRequest) SetUserIdList(val []int64) {
	p.UserIdList = val
}
func (p *SystemRoleUserRequest) SetUsername(val string) {
	p.Username = val
}
func (p *SystemRoleUserRequest) SetNickname(val string) {
	p.Nickname = val
}
func (p *SystemRoleUserRequest) SetPhone(val string) {
	p.Phone = val
}
func (p *SystemRoleUserRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemRoleUserRequest) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *SystemRoleUserRequest) SetCreatedBy(val *int64) {
	p.CreatedBy = val
}
func (p *SystemRoleUserRequest) SetUpdatedBy(val *int64) {
	p.UpdatedBy = val
}
func (p *SystemRoleUserRequest) SetCreateTime(val *int64) {
	p.CreateTime = val
}
func (p *SystemRoleUserRequest) SetUpdateTime(val *int64) {
	p.UpdateTime = val
}

func (p *SystemRoleUserRequest) IsSetCurrent() bool {
	return p.Current != SystemRoleUserRequest_Current_DEFAULT
}

func (p *SystemRoleUserRequest) IsSetSize() bool {
	return p.Size != SystemRoleUserRequest_Size_DEFAULT
}

func (p *SystemRoleUserRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *SystemRoleUserRequest) IsSetRoleId() bool {
	return p.RoleId != nil
}

func (p *SystemRoleUserRequest) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *SystemRoleUserRequest) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *SystemRoleUserRequest) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *SystemRoleUserRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *SystemRoleUserRequest) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *SystemRoleUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleUserRequest(%+v)", *p)
}

var fieldIDToName_SystemRoleUserRequest = map[int16]string{
	1:  "current",
	2:  "size",
	3:  "id",
	4:  "roleId",
	5:  "userIdList",
	6:  "username",
	7:  "nickname",
	8:  "phone",
	9:  "remark",
	10: "isDelete",
	11: "createdBy",
	12: "updatedBy",
	13: "createTime",
	14: "updateTime",
}

type SystemRoleUserResponse struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	RoleId     int64  `thrift:"roleId,2" frugal:"2,default,i64" json:"roleId"`
	RoleName   string `thrift:"roleName,3" frugal:"3,default,string" json:"roleName"`
	UserId     int64  `thrift:"userId,4" frugal:"4,default,i64" json:"userId"`
	Username   string `thrift:"username,5" frugal:"5,default,string" json:"username"`
	Nickname   string `thrift:"nickname,6" frugal:"6,default,string" json:"nickname"`
	Gender     int8   `thrift:"gender,7" frugal:"7,default,i8" json:"gender"`
	Avatar     string `thrift:"avatar,8" frugal:"8,default,string" json:"avatar"`
	Phone      string `thrift:"phone,9" frugal:"9,default,string" json:"phone"`
	Status     int8   `thrift:"status,10" frugal:"10,default,i8" json:"status"`
	Remark     string `thrift:"remark,11" frugal:"11,default,string" json:"remark"`
	IsDelete   int8   `thrift:"isDelete,12" frugal:"12,default,i8" json:"isDelete"`
	CreatedBy  int64  `thrift:"createdBy,13" frugal:"13,default,i64" json:"createdBy"`
	UpdatedBy  int64  `thrift:"updatedBy,14" frugal:"14,default,i64" json:"updatedBy"`
	CreateTime int64  `thrift:"createTime,15" frugal:"15,default,i64" json:"createTime"`
	UpdateTime int64  `thrift:"updateTime,16" frugal:"16,default,i64" json:"updateTime"`
}

func NewSystemRoleUserResponse() *SystemRoleUserResponse {
	return &SystemRoleUserResponse{}
}

func (p *SystemRoleUserResponse) InitDefault() {
}

func (p *SystemRoleUserResponse) GetId() (v int64) {
	return p.Id
}

func (p *SystemRoleUserResponse) GetRoleId() (v int64) {
	return p.RoleId
}

func (p *SystemRoleUserResponse) GetRoleName() (v string) {
	return p.RoleName
}

func (p *SystemRoleUserResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *SystemRoleUserResponse) GetUsername() (v string) {
	return p.Username
}

func (p *SystemRoleUserResponse) GetNickname() (v string) {
	return p.Nickname
}

func (p *SystemRoleUserResponse) GetGender() (v int8) {
	return p.Gender
}

func (p *SystemRoleUserResponse) GetAvatar() (v string) {
	return p.Avatar
}

func (p *SystemRoleUserResponse) GetPhone() (v string) {
	return p.Phone
}

func (p *SystemRoleUserResponse) GetStatus() (v int8) {
	return p.Status
}

func (p *SystemRoleUserResponse) GetRemark() (v string) {
	return p.Remark
}

func (p *SystemRoleUserResponse) GetIsDelete() (v int8) {
	return p.IsDelete
}

func (p *SystemRoleUserResponse) GetCreatedBy() (v int64) {
	return p.CreatedBy
}

func (p *SystemRoleUserResponse) GetUpdatedBy() (v int64) {
	return p.UpdatedBy
}

func (p *SystemRoleUserResponse) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *SystemRoleUserResponse) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *SystemRoleUserResponse) SetId(val int64) {
	p.Id = val
}
func (p *SystemRoleUserResponse) SetRoleId(val int64) {
	p.RoleId = val
}
func (p *SystemRoleUserResponse) SetRoleName(val string) {
	p.RoleName = val
}
func (p *SystemRoleUserResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *SystemRoleUserResponse) SetUsername(val string) {
	p.Username = val
}
func (p *SystemRoleUserResponse) SetNickname(val string) {
	p.Nickname = val
}
func (p *SystemRoleUserResponse) SetGender(val int8) {
	p.Gender = val
}
func (p *SystemRoleUserResponse) SetAvatar(val string) {
	p.Avatar = val
}
func (p *SystemRoleUserResponse) SetPhone(val string) {
	p.Phone = val
}
func (p *SystemRoleUserResponse) SetStatus(val int8) {
	p.Status = val
}
func (p *SystemRoleUserResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemRoleUserResponse) SetIsDelete(val int8) {
	p.IsDelete = val
}
func (p *SystemRoleUserResponse) SetCreatedBy(val int64) {
	p.CreatedBy = val
}
func (p *SystemRoleUserResponse) SetUpdatedBy(val int64) {
	p.UpdatedBy = val
}
func (p *SystemRoleUserResponse) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *SystemRoleUserResponse) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *SystemRoleUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleUserResponse(%+v)", *p)
}

var fieldIDToName_SystemRoleUserResponse = map[int16]string{
	1:  "id",
	2:  "roleId",
	3:  "roleName",
	4:  "userId",
	5:  "username",
	6:  "nickname",
	7:  "gender",
	8:  "avatar",
	9:  "phone",
	10: "status",
	11: "remark",
	12: "isDelete",
	13: "createdBy",
	14: "updatedBy",
	15: "createTime",
	16: "updateTime",
}

type SystemRoleUserPageResponse struct {
	Total   int64                     `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemRoleUserResponse `thrift:"records,2" frugal:"2,default,list<SystemRoleUserResponse>" json:"records"`
}

func NewSystemRoleUserPageResponse() *SystemRoleUserPageResponse {
	return &SystemRoleUserPageResponse{}
}

func (p *SystemRoleUserPageResponse) InitDefault() {
}

func (p *SystemRoleUserPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemRoleUserPageResponse) GetRecords() (v []*SystemRoleUserResponse) {
	return p.Records
}
func (p *SystemRoleUserPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemRoleUserPageResponse) SetRecords(val []*SystemRoleUserResponse) {
	p.Records = val
}

func (p *SystemRoleUserPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleUserPageResponse(%+v)", *p)
}

var fieldIDToName_SystemRoleUserPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
