// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/kouleen/idl/kitex_gen/common"
)

type MethodType int64

const (
	MethodType_GET     MethodType = 1
	MethodType_HEAD    MethodType = 2
	MethodType_POST    MethodType = 3
	MethodType_PUT     MethodType = 4
	MethodType_PATCH   MethodType = 5
	MethodType_DELETE  MethodType = 6
	MethodType_OPTIONS MethodType = 7
	MethodType_TRACE   MethodType = 8
)

func (p MethodType) String() string {
	switch p {
	case MethodType_GET:
		return "GET"
	case MethodType_HEAD:
		return "HEAD"
	case MethodType_POST:
		return "POST"
	case MethodType_PUT:
		return "PUT"
	case MethodType_PATCH:
		return "PATCH"
	case MethodType_DELETE:
		return "DELETE"
	case MethodType_OPTIONS:
		return "OPTIONS"
	case MethodType_TRACE:
		return "TRACE"
	}
	return "<UNSET>"
}

func MethodTypeFromString(s string) (MethodType, error) {
	switch s {
	case "GET":
		return MethodType_GET, nil
	case "HEAD":
		return MethodType_HEAD, nil
	case "POST":
		return MethodType_POST, nil
	case "PUT":
		return MethodType_PUT, nil
	case "PATCH":
		return MethodType_PATCH, nil
	case "DELETE":
		return MethodType_DELETE, nil
	case "OPTIONS":
		return MethodType_OPTIONS, nil
	case "TRACE":
		return MethodType_TRACE, nil
	}
	return MethodType(0), fmt.Errorf("not a valid MethodType string")
}

func MethodTypePtr(v MethodType) *MethodType { return &v }
func (p *MethodType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = MethodType(result.Int64)
	return
}

func (p *MethodType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type SystemInterfaceRequest struct {
	RequestPath   *string             `thrift:"requestPath,1,optional" frugal:"1,optional,string" json:"requestPath,omitempty"`
	InterfaceName *string             `thrift:"interfaceName,2,optional" frugal:"2,optional,string" json:"interfaceName,omitempty"`
	MethodType    *MethodType         `thrift:"methodType,3,optional" frugal:"3,optional,MethodType" json:"methodType,omitempty"`
	MethodName    *string             `thrift:"methodName,4,optional" frugal:"4,optional,string" json:"methodName,omitempty"`
	ParamTypes    *string             `thrift:"paramTypes,5,optional" frugal:"5,optional,string" json:"paramTypes,omitempty"`
	Version       *string             `thrift:"version,6,optional" frugal:"6,optional,string" json:"version,omitempty"`
	Status        *common.BaseStatus  `thrift:"status,7,optional" frugal:"7,optional,BaseStatus" json:"status,omitempty"`
	Remark        *string             `thrift:"remark,8,optional" frugal:"8,optional,string" json:"remark,omitempty"`
	PageRequest   *common.PageRequest `thrift:"PageRequest,9,optional" frugal:"9,optional,common.PageRequest" json:"PageRequest,omitempty"`
	BaseRequest   *common.BaseRequest `thrift:"BaseRequest,255,optional" frugal:"255,optional,common.BaseRequest" json:"BaseRequest,omitempty"`
}

func NewSystemInterfaceRequest() *SystemInterfaceRequest {
	return &SystemInterfaceRequest{}
}

func (p *SystemInterfaceRequest) InitDefault() {
}

var SystemInterfaceRequest_RequestPath_DEFAULT string

func (p *SystemInterfaceRequest) GetRequestPath() (v string) {
	if !p.IsSetRequestPath() {
		return SystemInterfaceRequest_RequestPath_DEFAULT
	}
	return *p.RequestPath
}

var SystemInterfaceRequest_InterfaceName_DEFAULT string

func (p *SystemInterfaceRequest) GetInterfaceName() (v string) {
	if !p.IsSetInterfaceName() {
		return SystemInterfaceRequest_InterfaceName_DEFAULT
	}
	return *p.InterfaceName
}

var SystemInterfaceRequest_MethodType_DEFAULT MethodType

func (p *SystemInterfaceRequest) GetMethodType() (v MethodType) {
	if !p.IsSetMethodType() {
		return SystemInterfaceRequest_MethodType_DEFAULT
	}
	return *p.MethodType
}

var SystemInterfaceRequest_MethodName_DEFAULT string

func (p *SystemInterfaceRequest) GetMethodName() (v string) {
	if !p.IsSetMethodName() {
		return SystemInterfaceRequest_MethodName_DEFAULT
	}
	return *p.MethodName
}

var SystemInterfaceRequest_ParamTypes_DEFAULT string

func (p *SystemInterfaceRequest) GetParamTypes() (v string) {
	if !p.IsSetParamTypes() {
		return SystemInterfaceRequest_ParamTypes_DEFAULT
	}
	return *p.ParamTypes
}

var SystemInterfaceRequest_Version_DEFAULT string

func (p *SystemInterfaceRequest) GetVersion() (v string) {
	if !p.IsSetVersion() {
		return SystemInterfaceRequest_Version_DEFAULT
	}
	return *p.Version
}

var SystemInterfaceRequest_Status_DEFAULT common.BaseStatus

func (p *SystemInterfaceRequest) GetStatus() (v common.BaseStatus) {
	if !p.IsSetStatus() {
		return SystemInterfaceRequest_Status_DEFAULT
	}
	return *p.Status
}

var SystemInterfaceRequest_Remark_DEFAULT string

func (p *SystemInterfaceRequest) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return SystemInterfaceRequest_Remark_DEFAULT
	}
	return *p.Remark
}

var SystemInterfaceRequest_PageRequest_DEFAULT *common.PageRequest

func (p *SystemInterfaceRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return SystemInterfaceRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var SystemInterfaceRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *SystemInterfaceRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return SystemInterfaceRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *SystemInterfaceRequest) SetRequestPath(val *string) {
	p.RequestPath = val
}
func (p *SystemInterfaceRequest) SetInterfaceName(val *string) {
	p.InterfaceName = val
}
func (p *SystemInterfaceRequest) SetMethodType(val *MethodType) {
	p.MethodType = val
}
func (p *SystemInterfaceRequest) SetMethodName(val *string) {
	p.MethodName = val
}
func (p *SystemInterfaceRequest) SetParamTypes(val *string) {
	p.ParamTypes = val
}
func (p *SystemInterfaceRequest) SetVersion(val *string) {
	p.Version = val
}
func (p *SystemInterfaceRequest) SetStatus(val *common.BaseStatus) {
	p.Status = val
}
func (p *SystemInterfaceRequest) SetRemark(val *string) {
	p.Remark = val
}
func (p *SystemInterfaceRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *SystemInterfaceRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *SystemInterfaceRequest) IsSetRequestPath() bool {
	return p.RequestPath != nil
}

func (p *SystemInterfaceRequest) IsSetInterfaceName() bool {
	return p.InterfaceName != nil
}

func (p *SystemInterfaceRequest) IsSetMethodType() bool {
	return p.MethodType != nil
}

func (p *SystemInterfaceRequest) IsSetMethodName() bool {
	return p.MethodName != nil
}

func (p *SystemInterfaceRequest) IsSetParamTypes() bool {
	return p.ParamTypes != nil
}

func (p *SystemInterfaceRequest) IsSetVersion() bool {
	return p.Version != nil
}

func (p *SystemInterfaceRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemInterfaceRequest) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *SystemInterfaceRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *SystemInterfaceRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *SystemInterfaceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemInterfaceRequest(%+v)", *p)
}

var fieldIDToName_SystemInterfaceRequest = map[int16]string{
	1:   "requestPath",
	2:   "interfaceName",
	3:   "methodType",
	4:   "methodName",
	5:   "paramTypes",
	6:   "version",
	7:   "status",
	8:   "remark",
	9:   "PageRequest",
	255: "BaseRequest",
}

type SystemInterfaceResponse struct {
	RequestPath   string               `thrift:"requestPath,1" frugal:"1,default,string" json:"requestPath"`
	InterfaceName string               `thrift:"interfaceName,2" frugal:"2,default,string" json:"interfaceName"`
	MethodType    MethodType           `thrift:"methodType,3" frugal:"3,default,MethodType" json:"methodType"`
	MethodName    string               `thrift:"methodName,4" frugal:"4,default,string" json:"methodName"`
	ParamTypes    string               `thrift:"paramTypes,5" frugal:"5,default,string" json:"paramTypes"`
	Version       string               `thrift:"version,6" frugal:"6,default,string" json:"version"`
	Status        common.BaseStatus    `thrift:"status,7" frugal:"7,default,BaseStatus" json:"status"`
	Remark        string               `thrift:"remark,8" frugal:"8,default,string" json:"remark"`
	BaseResponse  *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewSystemInterfaceResponse() *SystemInterfaceResponse {
	return &SystemInterfaceResponse{}
}

func (p *SystemInterfaceResponse) InitDefault() {
}

func (p *SystemInterfaceResponse) GetRequestPath() (v string) {
	return p.RequestPath
}

func (p *SystemInterfaceResponse) GetInterfaceName() (v string) {
	return p.InterfaceName
}

func (p *SystemInterfaceResponse) GetMethodType() (v MethodType) {
	return p.MethodType
}

func (p *SystemInterfaceResponse) GetMethodName() (v string) {
	return p.MethodName
}

func (p *SystemInterfaceResponse) GetParamTypes() (v string) {
	return p.ParamTypes
}

func (p *SystemInterfaceResponse) GetVersion() (v string) {
	return p.Version
}

func (p *SystemInterfaceResponse) GetStatus() (v common.BaseStatus) {
	return p.Status
}

func (p *SystemInterfaceResponse) GetRemark() (v string) {
	return p.Remark
}

var SystemInterfaceResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *SystemInterfaceResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return SystemInterfaceResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *SystemInterfaceResponse) SetRequestPath(val string) {
	p.RequestPath = val
}
func (p *SystemInterfaceResponse) SetInterfaceName(val string) {
	p.InterfaceName = val
}
func (p *SystemInterfaceResponse) SetMethodType(val MethodType) {
	p.MethodType = val
}
func (p *SystemInterfaceResponse) SetMethodName(val string) {
	p.MethodName = val
}
func (p *SystemInterfaceResponse) SetParamTypes(val string) {
	p.ParamTypes = val
}
func (p *SystemInterfaceResponse) SetVersion(val string) {
	p.Version = val
}
func (p *SystemInterfaceResponse) SetStatus(val common.BaseStatus) {
	p.Status = val
}
func (p *SystemInterfaceResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemInterfaceResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *SystemInterfaceResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *SystemInterfaceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemInterfaceResponse(%+v)", *p)
}

var fieldIDToName_SystemInterfaceResponse = map[int16]string{
	1:   "requestPath",
	2:   "interfaceName",
	3:   "methodType",
	4:   "methodName",
	5:   "paramTypes",
	6:   "version",
	7:   "status",
	8:   "remark",
	255: "BaseResponse",
}

type SystemInterfacePageResponse struct {
	Total   int64                      `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemInterfaceResponse `thrift:"records,2,required" frugal:"2,required,list<SystemInterfaceResponse>" json:"records"`
}

func NewSystemInterfacePageResponse() *SystemInterfacePageResponse {
	return &SystemInterfacePageResponse{}
}

func (p *SystemInterfacePageResponse) InitDefault() {
}

func (p *SystemInterfacePageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemInterfacePageResponse) GetRecords() (v []*SystemInterfaceResponse) {
	return p.Records
}
func (p *SystemInterfacePageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemInterfacePageResponse) SetRecords(val []*SystemInterfaceResponse) {
	p.Records = val
}

func (p *SystemInterfacePageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemInterfacePageResponse(%+v)", *p)
}

var fieldIDToName_SystemInterfacePageResponse = map[int16]string{
	1: "total",
	2: "records",
}
