// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
	"github.com/kouleen/idl/kitex_gen/common"
)

type SystemDictHeaderRequest struct {
	DictName    string              `thrift:"dictName,1" frugal:"1,default,string" json:"dictName"`
	DictType    string              `thrift:"dictType,2" frugal:"2,default,string" json:"dictType"`
	Status      *common.BaseStatus  `thrift:"status,3,optional" frugal:"3,optional,BaseStatus" json:"status,omitempty"`
	Remark      string              `thrift:"remark,4" frugal:"4,default,string" json:"remark"`
	PageRequest *common.PageRequest `thrift:"PageRequest,5" frugal:"5,default,common.PageRequest" json:"PageRequest"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255" frugal:"255,default,common.BaseRequest" json:"BaseRequest"`
}

func NewSystemDictHeaderRequest() *SystemDictHeaderRequest {
	return &SystemDictHeaderRequest{}
}

func (p *SystemDictHeaderRequest) InitDefault() {
}

func (p *SystemDictHeaderRequest) GetDictName() (v string) {
	return p.DictName
}

func (p *SystemDictHeaderRequest) GetDictType() (v string) {
	return p.DictType
}

var SystemDictHeaderRequest_Status_DEFAULT common.BaseStatus

func (p *SystemDictHeaderRequest) GetStatus() (v common.BaseStatus) {
	if !p.IsSetStatus() {
		return SystemDictHeaderRequest_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemDictHeaderRequest) GetRemark() (v string) {
	return p.Remark
}

var SystemDictHeaderRequest_PageRequest_DEFAULT *common.PageRequest

func (p *SystemDictHeaderRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return SystemDictHeaderRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var SystemDictHeaderRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *SystemDictHeaderRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return SystemDictHeaderRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *SystemDictHeaderRequest) SetDictName(val string) {
	p.DictName = val
}
func (p *SystemDictHeaderRequest) SetDictType(val string) {
	p.DictType = val
}
func (p *SystemDictHeaderRequest) SetStatus(val *common.BaseStatus) {
	p.Status = val
}
func (p *SystemDictHeaderRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemDictHeaderRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *SystemDictHeaderRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *SystemDictHeaderRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemDictHeaderRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *SystemDictHeaderRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *SystemDictHeaderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemDictHeaderRequest(%+v)", *p)
}

var fieldIDToName_SystemDictHeaderRequest = map[int16]string{
	1:   "dictName",
	2:   "dictType",
	3:   "status",
	4:   "remark",
	5:   "PageRequest",
	255: "BaseRequest",
}

type SystemDictHeaderResponse struct {
	DictName     string               `thrift:"dictName,1" frugal:"1,default,string" json:"dictName"`
	DictType     string               `thrift:"dictType,2" frugal:"2,default,string" json:"dictType"`
	Status       common.BaseStatus    `thrift:"status,3" frugal:"3,default,BaseStatus" json:"status"`
	Remark       string               `thrift:"remark,4" frugal:"4,default,string" json:"remark"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewSystemDictHeaderResponse() *SystemDictHeaderResponse {
	return &SystemDictHeaderResponse{}
}

func (p *SystemDictHeaderResponse) InitDefault() {
}

func (p *SystemDictHeaderResponse) GetDictName() (v string) {
	return p.DictName
}

func (p *SystemDictHeaderResponse) GetDictType() (v string) {
	return p.DictType
}

func (p *SystemDictHeaderResponse) GetStatus() (v common.BaseStatus) {
	return p.Status
}

func (p *SystemDictHeaderResponse) GetRemark() (v string) {
	return p.Remark
}

var SystemDictHeaderResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *SystemDictHeaderResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return SystemDictHeaderResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *SystemDictHeaderResponse) SetDictName(val string) {
	p.DictName = val
}
func (p *SystemDictHeaderResponse) SetDictType(val string) {
	p.DictType = val
}
func (p *SystemDictHeaderResponse) SetStatus(val common.BaseStatus) {
	p.Status = val
}
func (p *SystemDictHeaderResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemDictHeaderResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *SystemDictHeaderResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *SystemDictHeaderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemDictHeaderResponse(%+v)", *p)
}

var fieldIDToName_SystemDictHeaderResponse = map[int16]string{
	1:   "dictName",
	2:   "dictType",
	3:   "status",
	4:   "remark",
	255: "BaseResponse",
}

type SystemDictHeaderPageResponse struct {
	Total   int64                       `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemDictHeaderResponse `thrift:"records,2" frugal:"2,default,list<SystemDictHeaderResponse>" json:"records"`
}

func NewSystemDictHeaderPageResponse() *SystemDictHeaderPageResponse {
	return &SystemDictHeaderPageResponse{}
}

func (p *SystemDictHeaderPageResponse) InitDefault() {
}

func (p *SystemDictHeaderPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemDictHeaderPageResponse) GetRecords() (v []*SystemDictHeaderResponse) {
	return p.Records
}
func (p *SystemDictHeaderPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemDictHeaderPageResponse) SetRecords(val []*SystemDictHeaderResponse) {
	p.Records = val
}

func (p *SystemDictHeaderPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemDictHeaderPageResponse(%+v)", *p)
}

var fieldIDToName_SystemDictHeaderPageResponse = map[int16]string{
	1: "total",
	2: "records",
}

type SystemDictLineRequest struct {
	DictCode    string              `thrift:"dictCode,1" frugal:"1,default,string" json:"dictCode"`
	DictValue   string              `thrift:"dictValue,2" frugal:"2,default,string" json:"dictValue"`
	DictSort    *int32              `thrift:"dictSort,3,optional" frugal:"3,optional,i32" json:"dictSort,omitempty"`
	DictType    string              `thrift:"dictType,4" frugal:"4,default,string" json:"dictType"`
	ListClass   string              `thrift:"listClass,5" frugal:"5,default,string" json:"listClass"`
	Status      *common.BaseStatus  `thrift:"status,6,optional" frugal:"6,optional,BaseStatus" json:"status,omitempty"`
	Remark      string              `thrift:"remark,7" frugal:"7,default,string" json:"remark"`
	PageRequest *common.PageRequest `thrift:"PageRequest,8" frugal:"8,default,common.PageRequest" json:"PageRequest"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255" frugal:"255,default,common.BaseRequest" json:"BaseRequest"`
}

func NewSystemDictLineRequest() *SystemDictLineRequest {
	return &SystemDictLineRequest{}
}

func (p *SystemDictLineRequest) InitDefault() {
}

func (p *SystemDictLineRequest) GetDictCode() (v string) {
	return p.DictCode
}

func (p *SystemDictLineRequest) GetDictValue() (v string) {
	return p.DictValue
}

var SystemDictLineRequest_DictSort_DEFAULT int32

func (p *SystemDictLineRequest) GetDictSort() (v int32) {
	if !p.IsSetDictSort() {
		return SystemDictLineRequest_DictSort_DEFAULT
	}
	return *p.DictSort
}

func (p *SystemDictLineRequest) GetDictType() (v string) {
	return p.DictType
}

func (p *SystemDictLineRequest) GetListClass() (v string) {
	return p.ListClass
}

var SystemDictLineRequest_Status_DEFAULT common.BaseStatus

func (p *SystemDictLineRequest) GetStatus() (v common.BaseStatus) {
	if !p.IsSetStatus() {
		return SystemDictLineRequest_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemDictLineRequest) GetRemark() (v string) {
	return p.Remark
}

var SystemDictLineRequest_PageRequest_DEFAULT *common.PageRequest

func (p *SystemDictLineRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return SystemDictLineRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var SystemDictLineRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *SystemDictLineRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return SystemDictLineRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *SystemDictLineRequest) SetDictCode(val string) {
	p.DictCode = val
}
func (p *SystemDictLineRequest) SetDictValue(val string) {
	p.DictValue = val
}
func (p *SystemDictLineRequest) SetDictSort(val *int32) {
	p.DictSort = val
}
func (p *SystemDictLineRequest) SetDictType(val string) {
	p.DictType = val
}
func (p *SystemDictLineRequest) SetListClass(val string) {
	p.ListClass = val
}
func (p *SystemDictLineRequest) SetStatus(val *common.BaseStatus) {
	p.Status = val
}
func (p *SystemDictLineRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemDictLineRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *SystemDictLineRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *SystemDictLineRequest) IsSetDictSort() bool {
	return p.DictSort != nil
}

func (p *SystemDictLineRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemDictLineRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *SystemDictLineRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *SystemDictLineRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemDictLineRequest(%+v)", *p)
}

var fieldIDToName_SystemDictLineRequest = map[int16]string{
	1:   "dictCode",
	2:   "dictValue",
	3:   "dictSort",
	4:   "dictType",
	5:   "listClass",
	6:   "status",
	7:   "remark",
	8:   "PageRequest",
	255: "BaseRequest",
}

type SystemDictLineResponse struct {
	DictCode     string               `thrift:"dictCode,1" frugal:"1,default,string" json:"dictCode"`
	DictValue    string               `thrift:"dictValue,2" frugal:"2,default,string" json:"dictValue"`
	DictSort     int32                `thrift:"dictSort,3" frugal:"3,default,i32" json:"dictSort"`
	DictType     string               `thrift:"dictType,4" frugal:"4,default,string" json:"dictType"`
	ListClass    string               `thrift:"listClass,5" frugal:"5,default,string" json:"listClass"`
	Status       common.BaseStatus    `thrift:"status,6" frugal:"6,default,BaseStatus" json:"status"`
	Remark       string               `thrift:"remark,7" frugal:"7,default,string" json:"remark"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewSystemDictLineResponse() *SystemDictLineResponse {
	return &SystemDictLineResponse{}
}

func (p *SystemDictLineResponse) InitDefault() {
}

func (p *SystemDictLineResponse) GetDictCode() (v string) {
	return p.DictCode
}

func (p *SystemDictLineResponse) GetDictValue() (v string) {
	return p.DictValue
}

func (p *SystemDictLineResponse) GetDictSort() (v int32) {
	return p.DictSort
}

func (p *SystemDictLineResponse) GetDictType() (v string) {
	return p.DictType
}

func (p *SystemDictLineResponse) GetListClass() (v string) {
	return p.ListClass
}

func (p *SystemDictLineResponse) GetStatus() (v common.BaseStatus) {
	return p.Status
}

func (p *SystemDictLineResponse) GetRemark() (v string) {
	return p.Remark
}

var SystemDictLineResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *SystemDictLineResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return SystemDictLineResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *SystemDictLineResponse) SetDictCode(val string) {
	p.DictCode = val
}
func (p *SystemDictLineResponse) SetDictValue(val string) {
	p.DictValue = val
}
func (p *SystemDictLineResponse) SetDictSort(val int32) {
	p.DictSort = val
}
func (p *SystemDictLineResponse) SetDictType(val string) {
	p.DictType = val
}
func (p *SystemDictLineResponse) SetListClass(val string) {
	p.ListClass = val
}
func (p *SystemDictLineResponse) SetStatus(val common.BaseStatus) {
	p.Status = val
}
func (p *SystemDictLineResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemDictLineResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *SystemDictLineResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *SystemDictLineResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemDictLineResponse(%+v)", *p)
}

var fieldIDToName_SystemDictLineResponse = map[int16]string{
	1:   "dictCode",
	2:   "dictValue",
	3:   "dictSort",
	4:   "dictType",
	5:   "listClass",
	6:   "status",
	7:   "remark",
	255: "BaseResponse",
}

type SystemDictLinePageResponse struct {
	Total   int64                     `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemDictLineResponse `thrift:"records,2" frugal:"2,default,list<SystemDictLineResponse>" json:"records"`
}

func NewSystemDictLinePageResponse() *SystemDictLinePageResponse {
	return &SystemDictLinePageResponse{}
}

func (p *SystemDictLinePageResponse) InitDefault() {
}

func (p *SystemDictLinePageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemDictLinePageResponse) GetRecords() (v []*SystemDictLineResponse) {
	return p.Records
}
func (p *SystemDictLinePageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemDictLinePageResponse) SetRecords(val []*SystemDictLineResponse) {
	p.Records = val
}

func (p *SystemDictLinePageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemDictLinePageResponse(%+v)", *p)
}

var fieldIDToName_SystemDictLinePageResponse = map[int16]string{
	1: "total",
	2: "records",
}
