// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
)

type SystemBulletinRequest struct {
	Current    int64   `thrift:"current,1,optional" frugal:"1,optional,i64" json:"current,omitempty"`
	Size       int64   `thrift:"size,2,optional" frugal:"2,optional,i64" json:"size,omitempty"`
	Id         *int64  `thrift:"id,3,optional" frugal:"3,optional,i64" json:"id,omitempty"`
	Title      string  `thrift:"title,4" frugal:"4,default,string" json:"title"`
	Type       *int8   `thrift:"type,5,optional" frugal:"5,optional,i8" json:"type,omitempty"`
	Status     *int8   `thrift:"status,6,optional" frugal:"6,optional,i8" json:"status,omitempty"`
	Content    string  `thrift:"content,7" frugal:"7,default,string" json:"content"`
	IsDelete   *int8   `thrift:"isDelete,8,optional" frugal:"8,optional,i8" json:"isDelete,omitempty"`
	CreatedBy  *int64  `thrift:"createdBy,9,optional" frugal:"9,optional,i64" json:"createdBy,omitempty"`
	UpdatedBy  *int64  `thrift:"updatedBy,10,optional" frugal:"10,optional,i64" json:"updatedBy,omitempty"`
	CreateTime *int64  `thrift:"createTime,11,optional" frugal:"11,optional,i64" json:"createTime,omitempty"`
	UpdateTime *int64  `thrift:"updateTime,12,optional" frugal:"12,optional,i64" json:"updateTime,omitempty"`
	IdList     []int64 `thrift:"idList,13,optional" frugal:"13,optional,list<i64>" json:"idList,omitempty"`
}

func NewSystemBulletinRequest() *SystemBulletinRequest {
	return &SystemBulletinRequest{
		Current: 1,
		Size:    10,
	}
}

func (p *SystemBulletinRequest) InitDefault() {
	p.Current = 1
	p.Size = 10
}

var SystemBulletinRequest_Current_DEFAULT int64 = 1

func (p *SystemBulletinRequest) GetCurrent() (v int64) {
	if !p.IsSetCurrent() {
		return SystemBulletinRequest_Current_DEFAULT
	}
	return p.Current
}

var SystemBulletinRequest_Size_DEFAULT int64 = 10

func (p *SystemBulletinRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return SystemBulletinRequest_Size_DEFAULT
	}
	return p.Size
}

var SystemBulletinRequest_Id_DEFAULT int64

func (p *SystemBulletinRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return SystemBulletinRequest_Id_DEFAULT
	}
	return *p.Id
}

func (p *SystemBulletinRequest) GetTitle() (v string) {
	return p.Title
}

var SystemBulletinRequest_Type_DEFAULT int8

func (p *SystemBulletinRequest) GetType() (v int8) {
	if !p.IsSetType() {
		return SystemBulletinRequest_Type_DEFAULT
	}
	return *p.Type
}

var SystemBulletinRequest_Status_DEFAULT int8

func (p *SystemBulletinRequest) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return SystemBulletinRequest_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemBulletinRequest) GetContent() (v string) {
	return p.Content
}

var SystemBulletinRequest_IsDelete_DEFAULT int8

func (p *SystemBulletinRequest) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return SystemBulletinRequest_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

var SystemBulletinRequest_CreatedBy_DEFAULT int64

func (p *SystemBulletinRequest) GetCreatedBy() (v int64) {
	if !p.IsSetCreatedBy() {
		return SystemBulletinRequest_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var SystemBulletinRequest_UpdatedBy_DEFAULT int64

func (p *SystemBulletinRequest) GetUpdatedBy() (v int64) {
	if !p.IsSetUpdatedBy() {
		return SystemBulletinRequest_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var SystemBulletinRequest_CreateTime_DEFAULT int64

func (p *SystemBulletinRequest) GetCreateTime() (v int64) {
	if !p.IsSetCreateTime() {
		return SystemBulletinRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var SystemBulletinRequest_UpdateTime_DEFAULT int64

func (p *SystemBulletinRequest) GetUpdateTime() (v int64) {
	if !p.IsSetUpdateTime() {
		return SystemBulletinRequest_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}

var SystemBulletinRequest_IdList_DEFAULT []int64

func (p *SystemBulletinRequest) GetIdList() (v []int64) {
	if !p.IsSetIdList() {
		return SystemBulletinRequest_IdList_DEFAULT
	}
	return p.IdList
}
func (p *SystemBulletinRequest) SetCurrent(val int64) {
	p.Current = val
}
func (p *SystemBulletinRequest) SetSize(val int64) {
	p.Size = val
}
func (p *SystemBulletinRequest) SetId(val *int64) {
	p.Id = val
}
func (p *SystemBulletinRequest) SetTitle(val string) {
	p.Title = val
}
func (p *SystemBulletinRequest) SetType(val *int8) {
	p.Type = val
}
func (p *SystemBulletinRequest) SetStatus(val *int8) {
	p.Status = val
}
func (p *SystemBulletinRequest) SetContent(val string) {
	p.Content = val
}
func (p *SystemBulletinRequest) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *SystemBulletinRequest) SetCreatedBy(val *int64) {
	p.CreatedBy = val
}
func (p *SystemBulletinRequest) SetUpdatedBy(val *int64) {
	p.UpdatedBy = val
}
func (p *SystemBulletinRequest) SetCreateTime(val *int64) {
	p.CreateTime = val
}
func (p *SystemBulletinRequest) SetUpdateTime(val *int64) {
	p.UpdateTime = val
}
func (p *SystemBulletinRequest) SetIdList(val []int64) {
	p.IdList = val
}

func (p *SystemBulletinRequest) IsSetCurrent() bool {
	return p.Current != SystemBulletinRequest_Current_DEFAULT
}

func (p *SystemBulletinRequest) IsSetSize() bool {
	return p.Size != SystemBulletinRequest_Size_DEFAULT
}

func (p *SystemBulletinRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *SystemBulletinRequest) IsSetType() bool {
	return p.Type != nil
}

func (p *SystemBulletinRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemBulletinRequest) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *SystemBulletinRequest) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *SystemBulletinRequest) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *SystemBulletinRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *SystemBulletinRequest) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *SystemBulletinRequest) IsSetIdList() bool {
	return p.IdList != nil
}

func (p *SystemBulletinRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemBulletinRequest(%+v)", *p)
}

var fieldIDToName_SystemBulletinRequest = map[int16]string{
	1:  "current",
	2:  "size",
	3:  "id",
	4:  "title",
	5:  "type",
	6:  "status",
	7:  "content",
	8:  "isDelete",
	9:  "createdBy",
	10: "updatedBy",
	11: "createTime",
	12: "updateTime",
	13: "idList",
}

type SystemBulletinResponse struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Title      string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Type       *int8  `thrift:"type,3,optional" frugal:"3,optional,i8" json:"type,omitempty"`
	Status     *int8  `thrift:"status,4,optional" frugal:"4,optional,i8" json:"status,omitempty"`
	Content    string `thrift:"content,5" frugal:"5,default,string" json:"content"`
	IsDelete   *int8  `thrift:"isDelete,6,optional" frugal:"6,optional,i8" json:"isDelete,omitempty"`
	CreatedBy  int64  `thrift:"createdBy,7" frugal:"7,default,i64" json:"createdBy"`
	UpdatedBy  int64  `thrift:"updatedBy,8" frugal:"8,default,i64" json:"updatedBy"`
	CreateTime int64  `thrift:"createTime,9" frugal:"9,default,i64" json:"createTime"`
	UpdateTime int64  `thrift:"updateTime,10" frugal:"10,default,i64" json:"updateTime"`
}

func NewSystemBulletinResponse() *SystemBulletinResponse {
	return &SystemBulletinResponse{}
}

func (p *SystemBulletinResponse) InitDefault() {
}

func (p *SystemBulletinResponse) GetId() (v int64) {
	return p.Id
}

func (p *SystemBulletinResponse) GetTitle() (v string) {
	return p.Title
}

var SystemBulletinResponse_Type_DEFAULT int8

func (p *SystemBulletinResponse) GetType() (v int8) {
	if !p.IsSetType() {
		return SystemBulletinResponse_Type_DEFAULT
	}
	return *p.Type
}

var SystemBulletinResponse_Status_DEFAULT int8

func (p *SystemBulletinResponse) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return SystemBulletinResponse_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemBulletinResponse) GetContent() (v string) {
	return p.Content
}

var SystemBulletinResponse_IsDelete_DEFAULT int8

func (p *SystemBulletinResponse) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return SystemBulletinResponse_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

func (p *SystemBulletinResponse) GetCreatedBy() (v int64) {
	return p.CreatedBy
}

func (p *SystemBulletinResponse) GetUpdatedBy() (v int64) {
	return p.UpdatedBy
}

func (p *SystemBulletinResponse) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *SystemBulletinResponse) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *SystemBulletinResponse) SetId(val int64) {
	p.Id = val
}
func (p *SystemBulletinResponse) SetTitle(val string) {
	p.Title = val
}
func (p *SystemBulletinResponse) SetType(val *int8) {
	p.Type = val
}
func (p *SystemBulletinResponse) SetStatus(val *int8) {
	p.Status = val
}
func (p *SystemBulletinResponse) SetContent(val string) {
	p.Content = val
}
func (p *SystemBulletinResponse) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *SystemBulletinResponse) SetCreatedBy(val int64) {
	p.CreatedBy = val
}
func (p *SystemBulletinResponse) SetUpdatedBy(val int64) {
	p.UpdatedBy = val
}
func (p *SystemBulletinResponse) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *SystemBulletinResponse) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *SystemBulletinResponse) IsSetType() bool {
	return p.Type != nil
}

func (p *SystemBulletinResponse) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemBulletinResponse) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *SystemBulletinResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemBulletinResponse(%+v)", *p)
}

var fieldIDToName_SystemBulletinResponse = map[int16]string{
	1:  "id",
	2:  "title",
	3:  "type",
	4:  "status",
	5:  "content",
	6:  "isDelete",
	7:  "createdBy",
	8:  "updatedBy",
	9:  "createTime",
	10: "updateTime",
}

type SystemBulletinPageResponse struct {
	Total   int64                     `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemBulletinResponse `thrift:"records,2" frugal:"2,default,list<SystemBulletinResponse>" json:"records"`
}

func NewSystemBulletinPageResponse() *SystemBulletinPageResponse {
	return &SystemBulletinPageResponse{}
}

func (p *SystemBulletinPageResponse) InitDefault() {
}

func (p *SystemBulletinPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemBulletinPageResponse) GetRecords() (v []*SystemBulletinResponse) {
	return p.Records
}
func (p *SystemBulletinPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemBulletinPageResponse) SetRecords(val []*SystemBulletinResponse) {
	p.Records = val
}

func (p *SystemBulletinPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemBulletinPageResponse(%+v)", *p)
}

var fieldIDToName_SystemBulletinPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
