// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
)

type SystemTemplateRequest struct {
	Current         int64  `thrift:"current,1,optional" frugal:"1,optional,i64" json:"current,omitempty"`
	Size            int64  `thrift:"size,2,optional" frugal:"2,optional,i64" json:"size,omitempty"`
	Id              *int64 `thrift:"id,3,optional" frugal:"3,optional,i64" json:"id,omitempty"`
	TemplateCode    string `thrift:"templateCode,4" frugal:"4,default,string" json:"templateCode"`
	TemplateName    string `thrift:"templateName,5" frugal:"5,default,string" json:"templateName"`
	TemplateType    string `thrift:"templateType,6" frugal:"6,default,string" json:"templateType"`
	TemplateContent string `thrift:"templateContent,7" frugal:"7,default,string" json:"templateContent"`
	Status          *int8  `thrift:"status,8,optional" frugal:"8,optional,i8" json:"status,omitempty"`
	Remark          string `thrift:"remark,9" frugal:"9,default,string" json:"remark"`
	IsDelete        *int8  `thrift:"isDelete,10,optional" frugal:"10,optional,i8" json:"isDelete,omitempty"`
	CreatedBy       *int64 `thrift:"createdBy,11,optional" frugal:"11,optional,i64" json:"createdBy,omitempty"`
	UpdatedBy       *int64 `thrift:"updatedBy,12,optional" frugal:"12,optional,i64" json:"updatedBy,omitempty"`
	CreateTime      *int64 `thrift:"createTime,13,optional" frugal:"13,optional,i64" json:"createTime,omitempty"`
}

func NewSystemTemplateRequest() *SystemTemplateRequest {
	return &SystemTemplateRequest{
		Current: 1,
		Size:    10,
	}
}

func (p *SystemTemplateRequest) InitDefault() {
	p.Current = 1
	p.Size = 10
}

var SystemTemplateRequest_Current_DEFAULT int64 = 1

func (p *SystemTemplateRequest) GetCurrent() (v int64) {
	if !p.IsSetCurrent() {
		return SystemTemplateRequest_Current_DEFAULT
	}
	return p.Current
}

var SystemTemplateRequest_Size_DEFAULT int64 = 10

func (p *SystemTemplateRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return SystemTemplateRequest_Size_DEFAULT
	}
	return p.Size
}

var SystemTemplateRequest_Id_DEFAULT int64

func (p *SystemTemplateRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return SystemTemplateRequest_Id_DEFAULT
	}
	return *p.Id
}

func (p *SystemTemplateRequest) GetTemplateCode() (v string) {
	return p.TemplateCode
}

func (p *SystemTemplateRequest) GetTemplateName() (v string) {
	return p.TemplateName
}

func (p *SystemTemplateRequest) GetTemplateType() (v string) {
	return p.TemplateType
}

func (p *SystemTemplateRequest) GetTemplateContent() (v string) {
	return p.TemplateContent
}

var SystemTemplateRequest_Status_DEFAULT int8

func (p *SystemTemplateRequest) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return SystemTemplateRequest_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemTemplateRequest) GetRemark() (v string) {
	return p.Remark
}

var SystemTemplateRequest_IsDelete_DEFAULT int8

func (p *SystemTemplateRequest) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return SystemTemplateRequest_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

var SystemTemplateRequest_CreatedBy_DEFAULT int64

func (p *SystemTemplateRequest) GetCreatedBy() (v int64) {
	if !p.IsSetCreatedBy() {
		return SystemTemplateRequest_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var SystemTemplateRequest_UpdatedBy_DEFAULT int64

func (p *SystemTemplateRequest) GetUpdatedBy() (v int64) {
	if !p.IsSetUpdatedBy() {
		return SystemTemplateRequest_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var SystemTemplateRequest_CreateTime_DEFAULT int64

func (p *SystemTemplateRequest) GetCreateTime() (v int64) {
	if !p.IsSetCreateTime() {
		return SystemTemplateRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}
func (p *SystemTemplateRequest) SetCurrent(val int64) {
	p.Current = val
}
func (p *SystemTemplateRequest) SetSize(val int64) {
	p.Size = val
}
func (p *SystemTemplateRequest) SetId(val *int64) {
	p.Id = val
}
func (p *SystemTemplateRequest) SetTemplateCode(val string) {
	p.TemplateCode = val
}
func (p *SystemTemplateRequest) SetTemplateName(val string) {
	p.TemplateName = val
}
func (p *SystemTemplateRequest) SetTemplateType(val string) {
	p.TemplateType = val
}
func (p *SystemTemplateRequest) SetTemplateContent(val string) {
	p.TemplateContent = val
}
func (p *SystemTemplateRequest) SetStatus(val *int8) {
	p.Status = val
}
func (p *SystemTemplateRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemTemplateRequest) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *SystemTemplateRequest) SetCreatedBy(val *int64) {
	p.CreatedBy = val
}
func (p *SystemTemplateRequest) SetUpdatedBy(val *int64) {
	p.UpdatedBy = val
}
func (p *SystemTemplateRequest) SetCreateTime(val *int64) {
	p.CreateTime = val
}

func (p *SystemTemplateRequest) IsSetCurrent() bool {
	return p.Current != SystemTemplateRequest_Current_DEFAULT
}

func (p *SystemTemplateRequest) IsSetSize() bool {
	return p.Size != SystemTemplateRequest_Size_DEFAULT
}

func (p *SystemTemplateRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *SystemTemplateRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemTemplateRequest) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *SystemTemplateRequest) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *SystemTemplateRequest) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *SystemTemplateRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *SystemTemplateRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemTemplateRequest(%+v)", *p)
}

var fieldIDToName_SystemTemplateRequest = map[int16]string{
	1:  "current",
	2:  "size",
	3:  "id",
	4:  "templateCode",
	5:  "templateName",
	6:  "templateType",
	7:  "templateContent",
	8:  "status",
	9:  "remark",
	10: "isDelete",
	11: "createdBy",
	12: "updatedBy",
	13: "createTime",
}

type SystemTemplateResponse struct {
	Id              int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	TemplateCode    string `thrift:"templateCode,2" frugal:"2,default,string" json:"templateCode"`
	TemplateName    string `thrift:"templateName,3" frugal:"3,default,string" json:"templateName"`
	TemplateType    string `thrift:"templateType,4" frugal:"4,default,string" json:"templateType"`
	TemplateContent string `thrift:"templateContent,5" frugal:"5,default,string" json:"templateContent"`
	Status          int8   `thrift:"status,6" frugal:"6,default,i8" json:"status"`
	Remark          string `thrift:"remark,7" frugal:"7,default,string" json:"remark"`
	IsDelete        int8   `thrift:"isDelete,8" frugal:"8,default,i8" json:"isDelete"`
	CreatedBy       int64  `thrift:"createdBy,9" frugal:"9,default,i64" json:"createdBy"`
	UpdatedBy       int64  `thrift:"updatedBy,10" frugal:"10,default,i64" json:"updatedBy"`
	CreateTime      int64  `thrift:"createTime,11" frugal:"11,default,i64" json:"createTime"`
	UpdateTime      int64  `thrift:"updateTime,12" frugal:"12,default,i64" json:"updateTime"`
}

func NewSystemTemplateResponse() *SystemTemplateResponse {
	return &SystemTemplateResponse{}
}

func (p *SystemTemplateResponse) InitDefault() {
}

func (p *SystemTemplateResponse) GetId() (v int64) {
	return p.Id
}

func (p *SystemTemplateResponse) GetTemplateCode() (v string) {
	return p.TemplateCode
}

func (p *SystemTemplateResponse) GetTemplateName() (v string) {
	return p.TemplateName
}

func (p *SystemTemplateResponse) GetTemplateType() (v string) {
	return p.TemplateType
}

func (p *SystemTemplateResponse) GetTemplateContent() (v string) {
	return p.TemplateContent
}

func (p *SystemTemplateResponse) GetStatus() (v int8) {
	return p.Status
}

func (p *SystemTemplateResponse) GetRemark() (v string) {
	return p.Remark
}

func (p *SystemTemplateResponse) GetIsDelete() (v int8) {
	return p.IsDelete
}

func (p *SystemTemplateResponse) GetCreatedBy() (v int64) {
	return p.CreatedBy
}

func (p *SystemTemplateResponse) GetUpdatedBy() (v int64) {
	return p.UpdatedBy
}

func (p *SystemTemplateResponse) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *SystemTemplateResponse) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *SystemTemplateResponse) SetId(val int64) {
	p.Id = val
}
func (p *SystemTemplateResponse) SetTemplateCode(val string) {
	p.TemplateCode = val
}
func (p *SystemTemplateResponse) SetTemplateName(val string) {
	p.TemplateName = val
}
func (p *SystemTemplateResponse) SetTemplateType(val string) {
	p.TemplateType = val
}
func (p *SystemTemplateResponse) SetTemplateContent(val string) {
	p.TemplateContent = val
}
func (p *SystemTemplateResponse) SetStatus(val int8) {
	p.Status = val
}
func (p *SystemTemplateResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemTemplateResponse) SetIsDelete(val int8) {
	p.IsDelete = val
}
func (p *SystemTemplateResponse) SetCreatedBy(val int64) {
	p.CreatedBy = val
}
func (p *SystemTemplateResponse) SetUpdatedBy(val int64) {
	p.UpdatedBy = val
}
func (p *SystemTemplateResponse) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *SystemTemplateResponse) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *SystemTemplateResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemTemplateResponse(%+v)", *p)
}

var fieldIDToName_SystemTemplateResponse = map[int16]string{
	1:  "id",
	2:  "templateCode",
	3:  "templateName",
	4:  "templateType",
	5:  "templateContent",
	6:  "status",
	7:  "remark",
	8:  "isDelete",
	9:  "createdBy",
	10: "updatedBy",
	11: "createTime",
	12: "updateTime",
}

type SystemTemplatePageResponse struct {
	Total   int64                     `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemTemplateResponse `thrift:"records,2" frugal:"2,default,list<SystemTemplateResponse>" json:"records"`
}

func NewSystemTemplatePageResponse() *SystemTemplatePageResponse {
	return &SystemTemplatePageResponse{}
}

func (p *SystemTemplatePageResponse) InitDefault() {
}

func (p *SystemTemplatePageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemTemplatePageResponse) GetRecords() (v []*SystemTemplateResponse) {
	return p.Records
}
func (p *SystemTemplatePageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemTemplatePageResponse) SetRecords(val []*SystemTemplateResponse) {
	p.Records = val
}

func (p *SystemTemplatePageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemTemplatePageResponse(%+v)", *p)
}

var fieldIDToName_SystemTemplatePageResponse = map[int16]string{
	1: "total",
	2: "records",
}
