// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
	"github.com/kouleen/idl/kitex_gen/common"
)

type SystemRoleMenuRequest struct {
	RoleId      *int64              `thrift:"roleId,1,optional" frugal:"1,optional,i64" json:"roleId,omitempty"`
	RoleName    *string             `thrift:"roleName,2,optional" frugal:"2,optional,string" json:"roleName,omitempty"`
	RoleSort    *int32              `thrift:"roleSort,3,optional" frugal:"3,optional,i32" json:"roleSort,omitempty"`
	MenuIds     []int64             `thrift:"menuIds,4,optional" frugal:"4,optional,list<i64>" json:"menuIds,omitempty"`
	Status      *common.BaseStatus  `thrift:"status,5,optional" frugal:"5,optional,BaseStatus" json:"status,omitempty"`
	Remark      *string             `thrift:"remark,6,optional" frugal:"6,optional,string" json:"remark,omitempty"`
	PageRequest *common.PageRequest `thrift:"PageRequest,7,optional" frugal:"7,optional,common.PageRequest" json:"PageRequest,omitempty"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255,optional" frugal:"255,optional,common.BaseRequest" json:"BaseRequest,omitempty"`
}

func NewSystemRoleMenuRequest() *SystemRoleMenuRequest {
	return &SystemRoleMenuRequest{}
}

func (p *SystemRoleMenuRequest) InitDefault() {
}

var SystemRoleMenuRequest_RoleId_DEFAULT int64

func (p *SystemRoleMenuRequest) GetRoleId() (v int64) {
	if !p.IsSetRoleId() {
		return SystemRoleMenuRequest_RoleId_DEFAULT
	}
	return *p.RoleId
}

var SystemRoleMenuRequest_RoleName_DEFAULT string

func (p *SystemRoleMenuRequest) GetRoleName() (v string) {
	if !p.IsSetRoleName() {
		return SystemRoleMenuRequest_RoleName_DEFAULT
	}
	return *p.RoleName
}

var SystemRoleMenuRequest_RoleSort_DEFAULT int32

func (p *SystemRoleMenuRequest) GetRoleSort() (v int32) {
	if !p.IsSetRoleSort() {
		return SystemRoleMenuRequest_RoleSort_DEFAULT
	}
	return *p.RoleSort
}

var SystemRoleMenuRequest_MenuIds_DEFAULT []int64

func (p *SystemRoleMenuRequest) GetMenuIds() (v []int64) {
	if !p.IsSetMenuIds() {
		return SystemRoleMenuRequest_MenuIds_DEFAULT
	}
	return p.MenuIds
}

var SystemRoleMenuRequest_Status_DEFAULT common.BaseStatus

func (p *SystemRoleMenuRequest) GetStatus() (v common.BaseStatus) {
	if !p.IsSetStatus() {
		return SystemRoleMenuRequest_Status_DEFAULT
	}
	return *p.Status
}

var SystemRoleMenuRequest_Remark_DEFAULT string

func (p *SystemRoleMenuRequest) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return SystemRoleMenuRequest_Remark_DEFAULT
	}
	return *p.Remark
}

var SystemRoleMenuRequest_PageRequest_DEFAULT *common.PageRequest

func (p *SystemRoleMenuRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return SystemRoleMenuRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var SystemRoleMenuRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *SystemRoleMenuRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return SystemRoleMenuRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *SystemRoleMenuRequest) SetRoleId(val *int64) {
	p.RoleId = val
}
func (p *SystemRoleMenuRequest) SetRoleName(val *string) {
	p.RoleName = val
}
func (p *SystemRoleMenuRequest) SetRoleSort(val *int32) {
	p.RoleSort = val
}
func (p *SystemRoleMenuRequest) SetMenuIds(val []int64) {
	p.MenuIds = val
}
func (p *SystemRoleMenuRequest) SetStatus(val *common.BaseStatus) {
	p.Status = val
}
func (p *SystemRoleMenuRequest) SetRemark(val *string) {
	p.Remark = val
}
func (p *SystemRoleMenuRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *SystemRoleMenuRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *SystemRoleMenuRequest) IsSetRoleId() bool {
	return p.RoleId != nil
}

func (p *SystemRoleMenuRequest) IsSetRoleName() bool {
	return p.RoleName != nil
}

func (p *SystemRoleMenuRequest) IsSetRoleSort() bool {
	return p.RoleSort != nil
}

func (p *SystemRoleMenuRequest) IsSetMenuIds() bool {
	return p.MenuIds != nil
}

func (p *SystemRoleMenuRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemRoleMenuRequest) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *SystemRoleMenuRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *SystemRoleMenuRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *SystemRoleMenuRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleMenuRequest(%+v)", *p)
}

var fieldIDToName_SystemRoleMenuRequest = map[int16]string{
	1:   "roleId",
	2:   "roleName",
	3:   "roleSort",
	4:   "menuIds",
	5:   "status",
	6:   "remark",
	7:   "PageRequest",
	255: "BaseRequest",
}

type SystemRoleMenuResponse struct {
	RoleId       int64                `thrift:"roleId,1" frugal:"1,default,i64" json:"roleId"`
	MenuId       int64                `thrift:"menuId,2" frugal:"2,default,i64" json:"menuId"`
	Remark       string               `thrift:"remark,3" frugal:"3,default,string" json:"remark"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewSystemRoleMenuResponse() *SystemRoleMenuResponse {
	return &SystemRoleMenuResponse{}
}

func (p *SystemRoleMenuResponse) InitDefault() {
}

func (p *SystemRoleMenuResponse) GetRoleId() (v int64) {
	return p.RoleId
}

func (p *SystemRoleMenuResponse) GetMenuId() (v int64) {
	return p.MenuId
}

func (p *SystemRoleMenuResponse) GetRemark() (v string) {
	return p.Remark
}

var SystemRoleMenuResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *SystemRoleMenuResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return SystemRoleMenuResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *SystemRoleMenuResponse) SetRoleId(val int64) {
	p.RoleId = val
}
func (p *SystemRoleMenuResponse) SetMenuId(val int64) {
	p.MenuId = val
}
func (p *SystemRoleMenuResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemRoleMenuResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *SystemRoleMenuResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *SystemRoleMenuResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleMenuResponse(%+v)", *p)
}

var fieldIDToName_SystemRoleMenuResponse = map[int16]string{
	1:   "roleId",
	2:   "menuId",
	3:   "remark",
	255: "BaseResponse",
}

type SystemRoleMenuPageResponse struct {
	Total   int64                     `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemRoleMenuResponse `thrift:"records,2,required" frugal:"2,required,list<SystemRoleMenuResponse>" json:"records"`
}

func NewSystemRoleMenuPageResponse() *SystemRoleMenuPageResponse {
	return &SystemRoleMenuPageResponse{}
}

func (p *SystemRoleMenuPageResponse) InitDefault() {
}

func (p *SystemRoleMenuPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemRoleMenuPageResponse) GetRecords() (v []*SystemRoleMenuResponse) {
	return p.Records
}
func (p *SystemRoleMenuPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemRoleMenuPageResponse) SetRecords(val []*SystemRoleMenuResponse) {
	p.Records = val
}

func (p *SystemRoleMenuPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleMenuPageResponse(%+v)", *p)
}

var fieldIDToName_SystemRoleMenuPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
