// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
)

type SystemLoginLogRequest struct {
	Current    int64  `thrift:"current,1,optional" frugal:"1,optional,i64" json:"current,omitempty"`
	Size       int64  `thrift:"size,2,optional" frugal:"2,optional,i64" json:"size,omitempty"`
	Id         *int64 `thrift:"id,3,optional" frugal:"3,optional,i64" json:"id,omitempty"`
	Username   string `thrift:"username,4" frugal:"4,default,string" json:"username"`
	Ip         string `thrift:"ip,5" frugal:"5,default,string" json:"ip"`
	Location   string `thrift:"location,6" frugal:"6,default,string" json:"location"`
	Os         string `thrift:"os,7" frugal:"7,default,string" json:"os"`
	Token      string `thrift:"token,8" frugal:"8,default,string" json:"token"`
	Browser    string `thrift:"browser,9" frugal:"9,default,string" json:"browser"`
	Status     *int8  `thrift:"status,10,optional" frugal:"10,optional,i8" json:"status,omitempty"`
	Remark     string `thrift:"remark,11" frugal:"11,default,string" json:"remark"`
	IsDelete   *int8  `thrift:"isDelete,12,optional" frugal:"12,optional,i8" json:"isDelete,omitempty"`
	CreatedBy  *int64 `thrift:"createdBy,13,optional" frugal:"13,optional,i64" json:"createdBy,omitempty"`
	UpdatedBy  *int64 `thrift:"updatedBy,14,optional" frugal:"14,optional,i64" json:"updatedBy,omitempty"`
	CreateTime *int64 `thrift:"createTime,15,optional" frugal:"15,optional,i64" json:"createTime,omitempty"`
	UpdateTime *int64 `thrift:"updateTime,16,optional" frugal:"16,optional,i64" json:"updateTime,omitempty"`
}

func NewSystemLoginLogRequest() *SystemLoginLogRequest {
	return &SystemLoginLogRequest{
		Current: 1,
		Size:    10,
	}
}

func (p *SystemLoginLogRequest) InitDefault() {
	p.Current = 1
	p.Size = 10
}

var SystemLoginLogRequest_Current_DEFAULT int64 = 1

func (p *SystemLoginLogRequest) GetCurrent() (v int64) {
	if !p.IsSetCurrent() {
		return SystemLoginLogRequest_Current_DEFAULT
	}
	return p.Current
}

var SystemLoginLogRequest_Size_DEFAULT int64 = 10

func (p *SystemLoginLogRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return SystemLoginLogRequest_Size_DEFAULT
	}
	return p.Size
}

var SystemLoginLogRequest_Id_DEFAULT int64

func (p *SystemLoginLogRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return SystemLoginLogRequest_Id_DEFAULT
	}
	return *p.Id
}

func (p *SystemLoginLogRequest) GetUsername() (v string) {
	return p.Username
}

func (p *SystemLoginLogRequest) GetIp() (v string) {
	return p.Ip
}

func (p *SystemLoginLogRequest) GetLocation() (v string) {
	return p.Location
}

func (p *SystemLoginLogRequest) GetOs() (v string) {
	return p.Os
}

func (p *SystemLoginLogRequest) GetToken() (v string) {
	return p.Token
}

func (p *SystemLoginLogRequest) GetBrowser() (v string) {
	return p.Browser
}

var SystemLoginLogRequest_Status_DEFAULT int8

func (p *SystemLoginLogRequest) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return SystemLoginLogRequest_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemLoginLogRequest) GetRemark() (v string) {
	return p.Remark
}

var SystemLoginLogRequest_IsDelete_DEFAULT int8

func (p *SystemLoginLogRequest) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return SystemLoginLogRequest_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

var SystemLoginLogRequest_CreatedBy_DEFAULT int64

func (p *SystemLoginLogRequest) GetCreatedBy() (v int64) {
	if !p.IsSetCreatedBy() {
		return SystemLoginLogRequest_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var SystemLoginLogRequest_UpdatedBy_DEFAULT int64

func (p *SystemLoginLogRequest) GetUpdatedBy() (v int64) {
	if !p.IsSetUpdatedBy() {
		return SystemLoginLogRequest_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var SystemLoginLogRequest_CreateTime_DEFAULT int64

func (p *SystemLoginLogRequest) GetCreateTime() (v int64) {
	if !p.IsSetCreateTime() {
		return SystemLoginLogRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var SystemLoginLogRequest_UpdateTime_DEFAULT int64

func (p *SystemLoginLogRequest) GetUpdateTime() (v int64) {
	if !p.IsSetUpdateTime() {
		return SystemLoginLogRequest_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}
func (p *SystemLoginLogRequest) SetCurrent(val int64) {
	p.Current = val
}
func (p *SystemLoginLogRequest) SetSize(val int64) {
	p.Size = val
}
func (p *SystemLoginLogRequest) SetId(val *int64) {
	p.Id = val
}
func (p *SystemLoginLogRequest) SetUsername(val string) {
	p.Username = val
}
func (p *SystemLoginLogRequest) SetIp(val string) {
	p.Ip = val
}
func (p *SystemLoginLogRequest) SetLocation(val string) {
	p.Location = val
}
func (p *SystemLoginLogRequest) SetOs(val string) {
	p.Os = val
}
func (p *SystemLoginLogRequest) SetToken(val string) {
	p.Token = val
}
func (p *SystemLoginLogRequest) SetBrowser(val string) {
	p.Browser = val
}
func (p *SystemLoginLogRequest) SetStatus(val *int8) {
	p.Status = val
}
func (p *SystemLoginLogRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemLoginLogRequest) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *SystemLoginLogRequest) SetCreatedBy(val *int64) {
	p.CreatedBy = val
}
func (p *SystemLoginLogRequest) SetUpdatedBy(val *int64) {
	p.UpdatedBy = val
}
func (p *SystemLoginLogRequest) SetCreateTime(val *int64) {
	p.CreateTime = val
}
func (p *SystemLoginLogRequest) SetUpdateTime(val *int64) {
	p.UpdateTime = val
}

func (p *SystemLoginLogRequest) IsSetCurrent() bool {
	return p.Current != SystemLoginLogRequest_Current_DEFAULT
}

func (p *SystemLoginLogRequest) IsSetSize() bool {
	return p.Size != SystemLoginLogRequest_Size_DEFAULT
}

func (p *SystemLoginLogRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *SystemLoginLogRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemLoginLogRequest) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *SystemLoginLogRequest) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *SystemLoginLogRequest) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *SystemLoginLogRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *SystemLoginLogRequest) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *SystemLoginLogRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemLoginLogRequest(%+v)", *p)
}

var fieldIDToName_SystemLoginLogRequest = map[int16]string{
	1:  "current",
	2:  "size",
	3:  "id",
	4:  "username",
	5:  "ip",
	6:  "location",
	7:  "os",
	8:  "token",
	9:  "browser",
	10: "status",
	11: "remark",
	12: "isDelete",
	13: "createdBy",
	14: "updatedBy",
	15: "createTime",
	16: "updateTime",
}

type SystemLoginLogResponse struct {
	Id         int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Username   string `thrift:"username,4" frugal:"4,default,string" json:"username"`
	Ip         string `thrift:"ip,5" frugal:"5,default,string" json:"ip"`
	Location   string `thrift:"location,6" frugal:"6,default,string" json:"location"`
	Os         string `thrift:"os,7" frugal:"7,default,string" json:"os"`
	Token      string `thrift:"token,8" frugal:"8,default,string" json:"token"`
	Browser    string `thrift:"browser,9" frugal:"9,default,string" json:"browser"`
	Status     *int8  `thrift:"status,10,optional" frugal:"10,optional,i8" json:"status,omitempty"`
	Remark     string `thrift:"remark,11" frugal:"11,default,string" json:"remark"`
	IsDelete   *int8  `thrift:"isDelete,12,optional" frugal:"12,optional,i8" json:"isDelete,omitempty"`
	CreatedBy  int64  `thrift:"createdBy,13" frugal:"13,default,i64" json:"createdBy"`
	UpdatedBy  int64  `thrift:"updatedBy,14" frugal:"14,default,i64" json:"updatedBy"`
	CreateTime int64  `thrift:"createTime,15" frugal:"15,default,i64" json:"createTime"`
	UpdateTime int64  `thrift:"updateTime,16" frugal:"16,default,i64" json:"updateTime"`
}

func NewSystemLoginLogResponse() *SystemLoginLogResponse {
	return &SystemLoginLogResponse{}
}

func (p *SystemLoginLogResponse) InitDefault() {
}

func (p *SystemLoginLogResponse) GetId() (v int64) {
	return p.Id
}

func (p *SystemLoginLogResponse) GetUsername() (v string) {
	return p.Username
}

func (p *SystemLoginLogResponse) GetIp() (v string) {
	return p.Ip
}

func (p *SystemLoginLogResponse) GetLocation() (v string) {
	return p.Location
}

func (p *SystemLoginLogResponse) GetOs() (v string) {
	return p.Os
}

func (p *SystemLoginLogResponse) GetToken() (v string) {
	return p.Token
}

func (p *SystemLoginLogResponse) GetBrowser() (v string) {
	return p.Browser
}

var SystemLoginLogResponse_Status_DEFAULT int8

func (p *SystemLoginLogResponse) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return SystemLoginLogResponse_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemLoginLogResponse) GetRemark() (v string) {
	return p.Remark
}

var SystemLoginLogResponse_IsDelete_DEFAULT int8

func (p *SystemLoginLogResponse) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return SystemLoginLogResponse_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

func (p *SystemLoginLogResponse) GetCreatedBy() (v int64) {
	return p.CreatedBy
}

func (p *SystemLoginLogResponse) GetUpdatedBy() (v int64) {
	return p.UpdatedBy
}

func (p *SystemLoginLogResponse) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *SystemLoginLogResponse) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *SystemLoginLogResponse) SetId(val int64) {
	p.Id = val
}
func (p *SystemLoginLogResponse) SetUsername(val string) {
	p.Username = val
}
func (p *SystemLoginLogResponse) SetIp(val string) {
	p.Ip = val
}
func (p *SystemLoginLogResponse) SetLocation(val string) {
	p.Location = val
}
func (p *SystemLoginLogResponse) SetOs(val string) {
	p.Os = val
}
func (p *SystemLoginLogResponse) SetToken(val string) {
	p.Token = val
}
func (p *SystemLoginLogResponse) SetBrowser(val string) {
	p.Browser = val
}
func (p *SystemLoginLogResponse) SetStatus(val *int8) {
	p.Status = val
}
func (p *SystemLoginLogResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemLoginLogResponse) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *SystemLoginLogResponse) SetCreatedBy(val int64) {
	p.CreatedBy = val
}
func (p *SystemLoginLogResponse) SetUpdatedBy(val int64) {
	p.UpdatedBy = val
}
func (p *SystemLoginLogResponse) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *SystemLoginLogResponse) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *SystemLoginLogResponse) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemLoginLogResponse) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *SystemLoginLogResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemLoginLogResponse(%+v)", *p)
}

var fieldIDToName_SystemLoginLogResponse = map[int16]string{
	1:  "id",
	4:  "username",
	5:  "ip",
	6:  "location",
	7:  "os",
	8:  "token",
	9:  "browser",
	10: "status",
	11: "remark",
	12: "isDelete",
	13: "createdBy",
	14: "updatedBy",
	15: "createTime",
	16: "updateTime",
}

type SystemLoginLogPageResponse struct {
	Total   int64                     `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemLoginLogResponse `thrift:"records,2" frugal:"2,default,list<SystemLoginLogResponse>" json:"records"`
}

func NewSystemLoginLogPageResponse() *SystemLoginLogPageResponse {
	return &SystemLoginLogPageResponse{}
}

func (p *SystemLoginLogPageResponse) InitDefault() {
}

func (p *SystemLoginLogPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemLoginLogPageResponse) GetRecords() (v []*SystemLoginLogResponse) {
	return p.Records
}
func (p *SystemLoginLogPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemLoginLogPageResponse) SetRecords(val []*SystemLoginLogResponse) {
	p.Records = val
}

func (p *SystemLoginLogPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemLoginLogPageResponse(%+v)", *p)
}

var fieldIDToName_SystemLoginLogPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
