// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type MethodType int64

const (
	MethodType_GET     MethodType = 1
	MethodType_HEAD    MethodType = 2
	MethodType_POST    MethodType = 3
	MethodType_PUT     MethodType = 4
	MethodType_PATCH   MethodType = 5
	MethodType_DELETE  MethodType = 6
	MethodType_OPTIONS MethodType = 7
	MethodType_TRACE   MethodType = 8
)

func (p MethodType) String() string {
	switch p {
	case MethodType_GET:
		return "GET"
	case MethodType_HEAD:
		return "HEAD"
	case MethodType_POST:
		return "POST"
	case MethodType_PUT:
		return "PUT"
	case MethodType_PATCH:
		return "PATCH"
	case MethodType_DELETE:
		return "DELETE"
	case MethodType_OPTIONS:
		return "OPTIONS"
	case MethodType_TRACE:
		return "TRACE"
	}
	return "<UNSET>"
}

func MethodTypeFromString(s string) (MethodType, error) {
	switch s {
	case "GET":
		return MethodType_GET, nil
	case "HEAD":
		return MethodType_HEAD, nil
	case "POST":
		return MethodType_POST, nil
	case "PUT":
		return MethodType_PUT, nil
	case "PATCH":
		return MethodType_PATCH, nil
	case "DELETE":
		return MethodType_DELETE, nil
	case "OPTIONS":
		return MethodType_OPTIONS, nil
	case "TRACE":
		return MethodType_TRACE, nil
	}
	return MethodType(0), fmt.Errorf("not a valid MethodType string")
}

func MethodTypePtr(v MethodType) *MethodType { return &v }
func (p *MethodType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = MethodType(result.Int64)
	return
}

func (p *MethodType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type SystemInterfaceRequest struct {
	Current       int64  `thrift:"current,1,optional" frugal:"1,optional,i64" json:"current,omitempty"`
	Size          int64  `thrift:"size,2,optional" frugal:"2,optional,i64" json:"size,omitempty"`
	Id            *int64 `thrift:"id,3,optional" frugal:"3,optional,i64" json:"id,omitempty"`
	RequestPath   string `thrift:"requestPath,4" frugal:"4,default,string" json:"requestPath"`
	InterfaceName string `thrift:"interfaceName,5" frugal:"5,default,string" json:"interfaceName"`
	MethodType    *int8  `thrift:"methodType,6,optional" frugal:"6,optional,i8" json:"methodType,omitempty"`
	MethodName    string `thrift:"methodName,7" frugal:"7,default,string" json:"methodName"`
	ParamTypes    string `thrift:"paramTypes,8" frugal:"8,default,string" json:"paramTypes"`
	Version       string `thrift:"version,9" frugal:"9,default,string" json:"version"`
	Status        *int8  `thrift:"status,10,optional" frugal:"10,optional,i8" json:"status,omitempty"`
	Remark        string `thrift:"remark,11" frugal:"11,default,string" json:"remark"`
	IsDelete      *int8  `thrift:"isDelete,12,optional" frugal:"12,optional,i8" json:"isDelete,omitempty"`
	CreatedBy     *int64 `thrift:"createdBy,13,optional" frugal:"13,optional,i64" json:"createdBy,omitempty"`
	UpdatedBy     *int64 `thrift:"updatedBy,14,optional" frugal:"14,optional,i64" json:"updatedBy,omitempty"`
	CreateTime    *int64 `thrift:"createTime,15,optional" frugal:"15,optional,i64" json:"createTime,omitempty"`
	UpdateTime    *int64 `thrift:"updateTime,16,optional" frugal:"16,optional,i64" json:"updateTime,omitempty"`
}

func NewSystemInterfaceRequest() *SystemInterfaceRequest {
	return &SystemInterfaceRequest{
		Current: 1,
		Size:    10,
	}
}

func (p *SystemInterfaceRequest) InitDefault() {
	p.Current = 1
	p.Size = 10
}

var SystemInterfaceRequest_Current_DEFAULT int64 = 1

func (p *SystemInterfaceRequest) GetCurrent() (v int64) {
	if !p.IsSetCurrent() {
		return SystemInterfaceRequest_Current_DEFAULT
	}
	return p.Current
}

var SystemInterfaceRequest_Size_DEFAULT int64 = 10

func (p *SystemInterfaceRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return SystemInterfaceRequest_Size_DEFAULT
	}
	return p.Size
}

var SystemInterfaceRequest_Id_DEFAULT int64

func (p *SystemInterfaceRequest) GetId() (v int64) {
	if !p.IsSetId() {
		return SystemInterfaceRequest_Id_DEFAULT
	}
	return *p.Id
}

func (p *SystemInterfaceRequest) GetRequestPath() (v string) {
	return p.RequestPath
}

func (p *SystemInterfaceRequest) GetInterfaceName() (v string) {
	return p.InterfaceName
}

var SystemInterfaceRequest_MethodType_DEFAULT int8

func (p *SystemInterfaceRequest) GetMethodType() (v int8) {
	if !p.IsSetMethodType() {
		return SystemInterfaceRequest_MethodType_DEFAULT
	}
	return *p.MethodType
}

func (p *SystemInterfaceRequest) GetMethodName() (v string) {
	return p.MethodName
}

func (p *SystemInterfaceRequest) GetParamTypes() (v string) {
	return p.ParamTypes
}

func (p *SystemInterfaceRequest) GetVersion() (v string) {
	return p.Version
}

var SystemInterfaceRequest_Status_DEFAULT int8

func (p *SystemInterfaceRequest) GetStatus() (v int8) {
	if !p.IsSetStatus() {
		return SystemInterfaceRequest_Status_DEFAULT
	}
	return *p.Status
}

func (p *SystemInterfaceRequest) GetRemark() (v string) {
	return p.Remark
}

var SystemInterfaceRequest_IsDelete_DEFAULT int8

func (p *SystemInterfaceRequest) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return SystemInterfaceRequest_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

var SystemInterfaceRequest_CreatedBy_DEFAULT int64

func (p *SystemInterfaceRequest) GetCreatedBy() (v int64) {
	if !p.IsSetCreatedBy() {
		return SystemInterfaceRequest_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var SystemInterfaceRequest_UpdatedBy_DEFAULT int64

func (p *SystemInterfaceRequest) GetUpdatedBy() (v int64) {
	if !p.IsSetUpdatedBy() {
		return SystemInterfaceRequest_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var SystemInterfaceRequest_CreateTime_DEFAULT int64

func (p *SystemInterfaceRequest) GetCreateTime() (v int64) {
	if !p.IsSetCreateTime() {
		return SystemInterfaceRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var SystemInterfaceRequest_UpdateTime_DEFAULT int64

func (p *SystemInterfaceRequest) GetUpdateTime() (v int64) {
	if !p.IsSetUpdateTime() {
		return SystemInterfaceRequest_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}
func (p *SystemInterfaceRequest) SetCurrent(val int64) {
	p.Current = val
}
func (p *SystemInterfaceRequest) SetSize(val int64) {
	p.Size = val
}
func (p *SystemInterfaceRequest) SetId(val *int64) {
	p.Id = val
}
func (p *SystemInterfaceRequest) SetRequestPath(val string) {
	p.RequestPath = val
}
func (p *SystemInterfaceRequest) SetInterfaceName(val string) {
	p.InterfaceName = val
}
func (p *SystemInterfaceRequest) SetMethodType(val *int8) {
	p.MethodType = val
}
func (p *SystemInterfaceRequest) SetMethodName(val string) {
	p.MethodName = val
}
func (p *SystemInterfaceRequest) SetParamTypes(val string) {
	p.ParamTypes = val
}
func (p *SystemInterfaceRequest) SetVersion(val string) {
	p.Version = val
}
func (p *SystemInterfaceRequest) SetStatus(val *int8) {
	p.Status = val
}
func (p *SystemInterfaceRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemInterfaceRequest) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *SystemInterfaceRequest) SetCreatedBy(val *int64) {
	p.CreatedBy = val
}
func (p *SystemInterfaceRequest) SetUpdatedBy(val *int64) {
	p.UpdatedBy = val
}
func (p *SystemInterfaceRequest) SetCreateTime(val *int64) {
	p.CreateTime = val
}
func (p *SystemInterfaceRequest) SetUpdateTime(val *int64) {
	p.UpdateTime = val
}

func (p *SystemInterfaceRequest) IsSetCurrent() bool {
	return p.Current != SystemInterfaceRequest_Current_DEFAULT
}

func (p *SystemInterfaceRequest) IsSetSize() bool {
	return p.Size != SystemInterfaceRequest_Size_DEFAULT
}

func (p *SystemInterfaceRequest) IsSetId() bool {
	return p.Id != nil
}

func (p *SystemInterfaceRequest) IsSetMethodType() bool {
	return p.MethodType != nil
}

func (p *SystemInterfaceRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *SystemInterfaceRequest) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *SystemInterfaceRequest) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *SystemInterfaceRequest) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *SystemInterfaceRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *SystemInterfaceRequest) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *SystemInterfaceRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemInterfaceRequest(%+v)", *p)
}

var fieldIDToName_SystemInterfaceRequest = map[int16]string{
	1:  "current",
	2:  "size",
	3:  "id",
	4:  "requestPath",
	5:  "interfaceName",
	6:  "methodType",
	7:  "methodName",
	8:  "paramTypes",
	9:  "version",
	10: "status",
	11: "remark",
	12: "isDelete",
	13: "createdBy",
	14: "updatedBy",
	15: "createTime",
	16: "updateTime",
}

type SystemInterfaceResponse struct {
	Id            int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	RequestPath   string `thrift:"requestPath,2" frugal:"2,default,string" json:"requestPath"`
	InterfaceName string `thrift:"interfaceName,3" frugal:"3,default,string" json:"interfaceName"`
	MethodType    int8   `thrift:"methodType,4" frugal:"4,default,i8" json:"methodType"`
	MethodName    string `thrift:"methodName,5" frugal:"5,default,string" json:"methodName"`
	ParamTypes    string `thrift:"paramTypes,6" frugal:"6,default,string" json:"paramTypes"`
	Version       string `thrift:"version,7" frugal:"7,default,string" json:"version"`
	Status        int8   `thrift:"status,8" frugal:"8,default,i8" json:"status"`
	Remark        string `thrift:"remark,9" frugal:"9,default,string" json:"remark"`
	IsDelete      int8   `thrift:"isDelete,10" frugal:"10,default,i8" json:"isDelete"`
	CreatedBy     int64  `thrift:"createdBy,11" frugal:"11,default,i64" json:"createdBy"`
	UpdatedBy     int64  `thrift:"updatedBy,12" frugal:"12,default,i64" json:"updatedBy"`
	CreateTime    int64  `thrift:"createTime,13" frugal:"13,default,i64" json:"createTime"`
	UpdateTime    int64  `thrift:"updateTime,14" frugal:"14,default,i64" json:"updateTime"`
}

func NewSystemInterfaceResponse() *SystemInterfaceResponse {
	return &SystemInterfaceResponse{}
}

func (p *SystemInterfaceResponse) InitDefault() {
}

func (p *SystemInterfaceResponse) GetId() (v int64) {
	return p.Id
}

func (p *SystemInterfaceResponse) GetRequestPath() (v string) {
	return p.RequestPath
}

func (p *SystemInterfaceResponse) GetInterfaceName() (v string) {
	return p.InterfaceName
}

func (p *SystemInterfaceResponse) GetMethodType() (v int8) {
	return p.MethodType
}

func (p *SystemInterfaceResponse) GetMethodName() (v string) {
	return p.MethodName
}

func (p *SystemInterfaceResponse) GetParamTypes() (v string) {
	return p.ParamTypes
}

func (p *SystemInterfaceResponse) GetVersion() (v string) {
	return p.Version
}

func (p *SystemInterfaceResponse) GetStatus() (v int8) {
	return p.Status
}

func (p *SystemInterfaceResponse) GetRemark() (v string) {
	return p.Remark
}

func (p *SystemInterfaceResponse) GetIsDelete() (v int8) {
	return p.IsDelete
}

func (p *SystemInterfaceResponse) GetCreatedBy() (v int64) {
	return p.CreatedBy
}

func (p *SystemInterfaceResponse) GetUpdatedBy() (v int64) {
	return p.UpdatedBy
}

func (p *SystemInterfaceResponse) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *SystemInterfaceResponse) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *SystemInterfaceResponse) SetId(val int64) {
	p.Id = val
}
func (p *SystemInterfaceResponse) SetRequestPath(val string) {
	p.RequestPath = val
}
func (p *SystemInterfaceResponse) SetInterfaceName(val string) {
	p.InterfaceName = val
}
func (p *SystemInterfaceResponse) SetMethodType(val int8) {
	p.MethodType = val
}
func (p *SystemInterfaceResponse) SetMethodName(val string) {
	p.MethodName = val
}
func (p *SystemInterfaceResponse) SetParamTypes(val string) {
	p.ParamTypes = val
}
func (p *SystemInterfaceResponse) SetVersion(val string) {
	p.Version = val
}
func (p *SystemInterfaceResponse) SetStatus(val int8) {
	p.Status = val
}
func (p *SystemInterfaceResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemInterfaceResponse) SetIsDelete(val int8) {
	p.IsDelete = val
}
func (p *SystemInterfaceResponse) SetCreatedBy(val int64) {
	p.CreatedBy = val
}
func (p *SystemInterfaceResponse) SetUpdatedBy(val int64) {
	p.UpdatedBy = val
}
func (p *SystemInterfaceResponse) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *SystemInterfaceResponse) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *SystemInterfaceResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemInterfaceResponse(%+v)", *p)
}

var fieldIDToName_SystemInterfaceResponse = map[int16]string{
	1:  "id",
	2:  "requestPath",
	3:  "interfaceName",
	4:  "methodType",
	5:  "methodName",
	6:  "paramTypes",
	7:  "version",
	8:  "status",
	9:  "remark",
	10: "isDelete",
	11: "createdBy",
	12: "updatedBy",
	13: "createTime",
	14: "updateTime",
}

type SystemInterfacePageResponse struct {
	Total   int64                      `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemInterfaceResponse `thrift:"records,2" frugal:"2,default,list<SystemInterfaceResponse>" json:"records"`
}

func NewSystemInterfacePageResponse() *SystemInterfacePageResponse {
	return &SystemInterfacePageResponse{}
}

func (p *SystemInterfacePageResponse) InitDefault() {
}

func (p *SystemInterfacePageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemInterfacePageResponse) GetRecords() (v []*SystemInterfaceResponse) {
	return p.Records
}
func (p *SystemInterfacePageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemInterfacePageResponse) SetRecords(val []*SystemInterfaceResponse) {
	p.Records = val
}

func (p *SystemInterfacePageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemInterfacePageResponse(%+v)", *p)
}

var fieldIDToName_SystemInterfacePageResponse = map[int16]string{
	1: "total",
	2: "records",
}
