// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package system

import (
	"fmt"
	"github.com/kouleen/idl/kitex_gen/common"
)

type SystemRoleUserRequest struct {
	RoleId      *int64              `thrift:"roleId,1,optional" frugal:"1,optional,i64" json:"roleId,omitempty"`
	UserIdList  []int64             `thrift:"userIdList,2" frugal:"2,default,list<i64>" json:"userIdList"`
	Username    string              `thrift:"username,3" frugal:"3,default,string" json:"username"`
	Nickname    string              `thrift:"nickname,4" frugal:"4,default,string" json:"nickname"`
	Phone       string              `thrift:"phone,5" frugal:"5,default,string" json:"phone"`
	Remark      string              `thrift:"remark,6" frugal:"6,default,string" json:"remark"`
	PageRequest *common.PageRequest `thrift:"PageRequest,7" frugal:"7,default,common.PageRequest" json:"PageRequest"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255" frugal:"255,default,common.BaseRequest" json:"BaseRequest"`
}

func NewSystemRoleUserRequest() *SystemRoleUserRequest {
	return &SystemRoleUserRequest{}
}

func (p *SystemRoleUserRequest) InitDefault() {
}

var SystemRoleUserRequest_RoleId_DEFAULT int64

func (p *SystemRoleUserRequest) GetRoleId() (v int64) {
	if !p.IsSetRoleId() {
		return SystemRoleUserRequest_RoleId_DEFAULT
	}
	return *p.RoleId
}

func (p *SystemRoleUserRequest) GetUserIdList() (v []int64) {
	return p.UserIdList
}

func (p *SystemRoleUserRequest) GetUsername() (v string) {
	return p.Username
}

func (p *SystemRoleUserRequest) GetNickname() (v string) {
	return p.Nickname
}

func (p *SystemRoleUserRequest) GetPhone() (v string) {
	return p.Phone
}

func (p *SystemRoleUserRequest) GetRemark() (v string) {
	return p.Remark
}

var SystemRoleUserRequest_PageRequest_DEFAULT *common.PageRequest

func (p *SystemRoleUserRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return SystemRoleUserRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var SystemRoleUserRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *SystemRoleUserRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return SystemRoleUserRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *SystemRoleUserRequest) SetRoleId(val *int64) {
	p.RoleId = val
}
func (p *SystemRoleUserRequest) SetUserIdList(val []int64) {
	p.UserIdList = val
}
func (p *SystemRoleUserRequest) SetUsername(val string) {
	p.Username = val
}
func (p *SystemRoleUserRequest) SetNickname(val string) {
	p.Nickname = val
}
func (p *SystemRoleUserRequest) SetPhone(val string) {
	p.Phone = val
}
func (p *SystemRoleUserRequest) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemRoleUserRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *SystemRoleUserRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *SystemRoleUserRequest) IsSetRoleId() bool {
	return p.RoleId != nil
}

func (p *SystemRoleUserRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *SystemRoleUserRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *SystemRoleUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleUserRequest(%+v)", *p)
}

var fieldIDToName_SystemRoleUserRequest = map[int16]string{
	1:   "roleId",
	2:   "userIdList",
	3:   "username",
	4:   "nickname",
	5:   "phone",
	6:   "remark",
	7:   "PageRequest",
	255: "BaseRequest",
}

type SystemRoleUserResponse struct {
	RoleId       int64                `thrift:"roleId,1" frugal:"1,default,i64" json:"roleId"`
	RoleName     string               `thrift:"roleName,2" frugal:"2,default,string" json:"roleName"`
	UserId       int64                `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	Username     string               `thrift:"username,4" frugal:"4,default,string" json:"username"`
	Nickname     string               `thrift:"nickname,5" frugal:"5,default,string" json:"nickname"`
	Gender       int32                `thrift:"gender,6" frugal:"6,default,i32" json:"gender"`
	Avatar       string               `thrift:"avatar,7" frugal:"7,default,string" json:"avatar"`
	Phone        string               `thrift:"phone,8" frugal:"8,default,string" json:"phone"`
	Status       common.BaseStatus    `thrift:"status,9" frugal:"9,default,BaseStatus" json:"status"`
	Remark       string               `thrift:"remark,10" frugal:"10,default,string" json:"remark"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewSystemRoleUserResponse() *SystemRoleUserResponse {
	return &SystemRoleUserResponse{}
}

func (p *SystemRoleUserResponse) InitDefault() {
}

func (p *SystemRoleUserResponse) GetRoleId() (v int64) {
	return p.RoleId
}

func (p *SystemRoleUserResponse) GetRoleName() (v string) {
	return p.RoleName
}

func (p *SystemRoleUserResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *SystemRoleUserResponse) GetUsername() (v string) {
	return p.Username
}

func (p *SystemRoleUserResponse) GetNickname() (v string) {
	return p.Nickname
}

func (p *SystemRoleUserResponse) GetGender() (v int32) {
	return p.Gender
}

func (p *SystemRoleUserResponse) GetAvatar() (v string) {
	return p.Avatar
}

func (p *SystemRoleUserResponse) GetPhone() (v string) {
	return p.Phone
}

func (p *SystemRoleUserResponse) GetStatus() (v common.BaseStatus) {
	return p.Status
}

func (p *SystemRoleUserResponse) GetRemark() (v string) {
	return p.Remark
}

var SystemRoleUserResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *SystemRoleUserResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return SystemRoleUserResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *SystemRoleUserResponse) SetRoleId(val int64) {
	p.RoleId = val
}
func (p *SystemRoleUserResponse) SetRoleName(val string) {
	p.RoleName = val
}
func (p *SystemRoleUserResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *SystemRoleUserResponse) SetUsername(val string) {
	p.Username = val
}
func (p *SystemRoleUserResponse) SetNickname(val string) {
	p.Nickname = val
}
func (p *SystemRoleUserResponse) SetGender(val int32) {
	p.Gender = val
}
func (p *SystemRoleUserResponse) SetAvatar(val string) {
	p.Avatar = val
}
func (p *SystemRoleUserResponse) SetPhone(val string) {
	p.Phone = val
}
func (p *SystemRoleUserResponse) SetStatus(val common.BaseStatus) {
	p.Status = val
}
func (p *SystemRoleUserResponse) SetRemark(val string) {
	p.Remark = val
}
func (p *SystemRoleUserResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *SystemRoleUserResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *SystemRoleUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleUserResponse(%+v)", *p)
}

var fieldIDToName_SystemRoleUserResponse = map[int16]string{
	1:   "roleId",
	2:   "roleName",
	3:   "userId",
	4:   "username",
	5:   "nickname",
	6:   "gender",
	7:   "avatar",
	8:   "phone",
	9:   "status",
	10:  "remark",
	255: "BaseResponse",
}

type SystemRoleUserPageResponse struct {
	Total   int64                     `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*SystemRoleUserResponse `thrift:"records,2" frugal:"2,default,list<SystemRoleUserResponse>" json:"records"`
}

func NewSystemRoleUserPageResponse() *SystemRoleUserPageResponse {
	return &SystemRoleUserPageResponse{}
}

func (p *SystemRoleUserPageResponse) InitDefault() {
}

func (p *SystemRoleUserPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *SystemRoleUserPageResponse) GetRecords() (v []*SystemRoleUserResponse) {
	return p.Records
}
func (p *SystemRoleUserPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *SystemRoleUserPageResponse) SetRecords(val []*SystemRoleUserResponse) {
	p.Records = val
}

func (p *SystemRoleUserPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SystemRoleUserPageResponse(%+v)", *p)
}

var fieldIDToName_SystemRoleUserPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
