// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user_position

import (
	"fmt"
)

type UserPositionRequest struct {
	Current     int64    `thrift:"current,1,optional" frugal:"1,optional,i64" json:"current,omitempty"`
	Size        int64    `thrift:"size,2,optional" frugal:"2,optional,i64" json:"size,omitempty"`
	UserId      *int64   `thrift:"userId,3,optional" frugal:"3,optional,i64" json:"userId,omitempty"`
	Latitude    *float64 `thrift:"latitude,4,optional" frugal:"4,optional,double" json:"latitude,omitempty"`
	Longitude   *float64 `thrift:"longitude,5,optional" frugal:"5,optional,double" json:"longitude,omitempty"`
	Province    string   `thrift:"province,6" frugal:"6,default,string" json:"province"`
	City        string   `thrift:"city,7" frugal:"7,default,string" json:"city"`
	District    string   `thrift:"district,8" frugal:"8,default,string" json:"district"`
	Street      string   `thrift:"street,9" frugal:"9,default,string" json:"street"`
	FullAddress string   `thrift:"fullAddress,10" frugal:"10,default,string" json:"fullAddress"`
	Country     string   `thrift:"country,11" frugal:"11,default,string" json:"country"`
	CountryCode string   `thrift:"countryCode,12" frugal:"12,default,string" json:"countryCode"`
	IsDelete    *int8    `thrift:"isDelete,13,optional" frugal:"13,optional,i8" json:"isDelete,omitempty"`
	CreatedBy   *int64   `thrift:"createdBy,14,optional" frugal:"14,optional,i64" json:"createdBy,omitempty"`
	UpdatedBy   *int64   `thrift:"updatedBy,15,optional" frugal:"15,optional,i64" json:"updatedBy,omitempty"`
	CreateTime  *int64   `thrift:"createTime,16,optional" frugal:"16,optional,i64" json:"createTime,omitempty"`
	UpdateTime  *int64   `thrift:"updateTime,17,optional" frugal:"17,optional,i64" json:"updateTime,omitempty"`
}

func NewUserPositionRequest() *UserPositionRequest {
	return &UserPositionRequest{
		Current: 1,
		Size:    10,
	}
}

func (p *UserPositionRequest) InitDefault() {
	p.Current = 1
	p.Size = 10
}

var UserPositionRequest_Current_DEFAULT int64 = 1

func (p *UserPositionRequest) GetCurrent() (v int64) {
	if !p.IsSetCurrent() {
		return UserPositionRequest_Current_DEFAULT
	}
	return p.Current
}

var UserPositionRequest_Size_DEFAULT int64 = 10

func (p *UserPositionRequest) GetSize() (v int64) {
	if !p.IsSetSize() {
		return UserPositionRequest_Size_DEFAULT
	}
	return p.Size
}

var UserPositionRequest_UserId_DEFAULT int64

func (p *UserPositionRequest) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return UserPositionRequest_UserId_DEFAULT
	}
	return *p.UserId
}

var UserPositionRequest_Latitude_DEFAULT float64

func (p *UserPositionRequest) GetLatitude() (v float64) {
	if !p.IsSetLatitude() {
		return UserPositionRequest_Latitude_DEFAULT
	}
	return *p.Latitude
}

var UserPositionRequest_Longitude_DEFAULT float64

func (p *UserPositionRequest) GetLongitude() (v float64) {
	if !p.IsSetLongitude() {
		return UserPositionRequest_Longitude_DEFAULT
	}
	return *p.Longitude
}

func (p *UserPositionRequest) GetProvince() (v string) {
	return p.Province
}

func (p *UserPositionRequest) GetCity() (v string) {
	return p.City
}

func (p *UserPositionRequest) GetDistrict() (v string) {
	return p.District
}

func (p *UserPositionRequest) GetStreet() (v string) {
	return p.Street
}

func (p *UserPositionRequest) GetFullAddress() (v string) {
	return p.FullAddress
}

func (p *UserPositionRequest) GetCountry() (v string) {
	return p.Country
}

func (p *UserPositionRequest) GetCountryCode() (v string) {
	return p.CountryCode
}

var UserPositionRequest_IsDelete_DEFAULT int8

func (p *UserPositionRequest) GetIsDelete() (v int8) {
	if !p.IsSetIsDelete() {
		return UserPositionRequest_IsDelete_DEFAULT
	}
	return *p.IsDelete
}

var UserPositionRequest_CreatedBy_DEFAULT int64

func (p *UserPositionRequest) GetCreatedBy() (v int64) {
	if !p.IsSetCreatedBy() {
		return UserPositionRequest_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var UserPositionRequest_UpdatedBy_DEFAULT int64

func (p *UserPositionRequest) GetUpdatedBy() (v int64) {
	if !p.IsSetUpdatedBy() {
		return UserPositionRequest_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var UserPositionRequest_CreateTime_DEFAULT int64

func (p *UserPositionRequest) GetCreateTime() (v int64) {
	if !p.IsSetCreateTime() {
		return UserPositionRequest_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var UserPositionRequest_UpdateTime_DEFAULT int64

func (p *UserPositionRequest) GetUpdateTime() (v int64) {
	if !p.IsSetUpdateTime() {
		return UserPositionRequest_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}
func (p *UserPositionRequest) SetCurrent(val int64) {
	p.Current = val
}
func (p *UserPositionRequest) SetSize(val int64) {
	p.Size = val
}
func (p *UserPositionRequest) SetUserId(val *int64) {
	p.UserId = val
}
func (p *UserPositionRequest) SetLatitude(val *float64) {
	p.Latitude = val
}
func (p *UserPositionRequest) SetLongitude(val *float64) {
	p.Longitude = val
}
func (p *UserPositionRequest) SetProvince(val string) {
	p.Province = val
}
func (p *UserPositionRequest) SetCity(val string) {
	p.City = val
}
func (p *UserPositionRequest) SetDistrict(val string) {
	p.District = val
}
func (p *UserPositionRequest) SetStreet(val string) {
	p.Street = val
}
func (p *UserPositionRequest) SetFullAddress(val string) {
	p.FullAddress = val
}
func (p *UserPositionRequest) SetCountry(val string) {
	p.Country = val
}
func (p *UserPositionRequest) SetCountryCode(val string) {
	p.CountryCode = val
}
func (p *UserPositionRequest) SetIsDelete(val *int8) {
	p.IsDelete = val
}
func (p *UserPositionRequest) SetCreatedBy(val *int64) {
	p.CreatedBy = val
}
func (p *UserPositionRequest) SetUpdatedBy(val *int64) {
	p.UpdatedBy = val
}
func (p *UserPositionRequest) SetCreateTime(val *int64) {
	p.CreateTime = val
}
func (p *UserPositionRequest) SetUpdateTime(val *int64) {
	p.UpdateTime = val
}

func (p *UserPositionRequest) IsSetCurrent() bool {
	return p.Current != UserPositionRequest_Current_DEFAULT
}

func (p *UserPositionRequest) IsSetSize() bool {
	return p.Size != UserPositionRequest_Size_DEFAULT
}

func (p *UserPositionRequest) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *UserPositionRequest) IsSetLatitude() bool {
	return p.Latitude != nil
}

func (p *UserPositionRequest) IsSetLongitude() bool {
	return p.Longitude != nil
}

func (p *UserPositionRequest) IsSetIsDelete() bool {
	return p.IsDelete != nil
}

func (p *UserPositionRequest) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *UserPositionRequest) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *UserPositionRequest) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *UserPositionRequest) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *UserPositionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionRequest(%+v)", *p)
}

var fieldIDToName_UserPositionRequest = map[int16]string{
	1:  "current",
	2:  "size",
	3:  "userId",
	4:  "latitude",
	5:  "longitude",
	6:  "province",
	7:  "city",
	8:  "district",
	9:  "street",
	10: "fullAddress",
	11: "country",
	12: "countryCode",
	13: "isDelete",
	14: "createdBy",
	15: "updatedBy",
	16: "createTime",
	17: "updateTime",
}

type UserPositionResponse struct {
	Id          int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId      int64   `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Latitude    float64 `thrift:"latitude,3" frugal:"3,default,double" json:"latitude"`
	Longitude   float64 `thrift:"longitude,4" frugal:"4,default,double" json:"longitude"`
	Province    string  `thrift:"province,5" frugal:"5,default,string" json:"province"`
	City        string  `thrift:"city,6" frugal:"6,default,string" json:"city"`
	District    string  `thrift:"district,7" frugal:"7,default,string" json:"district"`
	Street      string  `thrift:"street,8" frugal:"8,default,string" json:"street"`
	FullAddress string  `thrift:"fullAddress,9" frugal:"9,default,string" json:"fullAddress"`
	Country     string  `thrift:"country,10" frugal:"10,default,string" json:"country"`
	CountryCode string  `thrift:"countryCode,11" frugal:"11,default,string" json:"countryCode"`
	IsDelete    int8    `thrift:"isDelete,12" frugal:"12,default,i8" json:"isDelete"`
	CreatedBy   int64   `thrift:"createdBy,13" frugal:"13,default,i64" json:"createdBy"`
	UpdatedBy   int64   `thrift:"updatedBy,14" frugal:"14,default,i64" json:"updatedBy"`
	CreateTime  int64   `thrift:"createTime,15" frugal:"15,default,i64" json:"createTime"`
	UpdateTime  int64   `thrift:"updateTime,16" frugal:"16,default,i64" json:"updateTime"`
}

func NewUserPositionResponse() *UserPositionResponse {
	return &UserPositionResponse{}
}

func (p *UserPositionResponse) InitDefault() {
}

func (p *UserPositionResponse) GetId() (v int64) {
	return p.Id
}

func (p *UserPositionResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserPositionResponse) GetLatitude() (v float64) {
	return p.Latitude
}

func (p *UserPositionResponse) GetLongitude() (v float64) {
	return p.Longitude
}

func (p *UserPositionResponse) GetProvince() (v string) {
	return p.Province
}

func (p *UserPositionResponse) GetCity() (v string) {
	return p.City
}

func (p *UserPositionResponse) GetDistrict() (v string) {
	return p.District
}

func (p *UserPositionResponse) GetStreet() (v string) {
	return p.Street
}

func (p *UserPositionResponse) GetFullAddress() (v string) {
	return p.FullAddress
}

func (p *UserPositionResponse) GetCountry() (v string) {
	return p.Country
}

func (p *UserPositionResponse) GetCountryCode() (v string) {
	return p.CountryCode
}

func (p *UserPositionResponse) GetIsDelete() (v int8) {
	return p.IsDelete
}

func (p *UserPositionResponse) GetCreatedBy() (v int64) {
	return p.CreatedBy
}

func (p *UserPositionResponse) GetUpdatedBy() (v int64) {
	return p.UpdatedBy
}

func (p *UserPositionResponse) GetCreateTime() (v int64) {
	return p.CreateTime
}

func (p *UserPositionResponse) GetUpdateTime() (v int64) {
	return p.UpdateTime
}
func (p *UserPositionResponse) SetId(val int64) {
	p.Id = val
}
func (p *UserPositionResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserPositionResponse) SetLatitude(val float64) {
	p.Latitude = val
}
func (p *UserPositionResponse) SetLongitude(val float64) {
	p.Longitude = val
}
func (p *UserPositionResponse) SetProvince(val string) {
	p.Province = val
}
func (p *UserPositionResponse) SetCity(val string) {
	p.City = val
}
func (p *UserPositionResponse) SetDistrict(val string) {
	p.District = val
}
func (p *UserPositionResponse) SetStreet(val string) {
	p.Street = val
}
func (p *UserPositionResponse) SetFullAddress(val string) {
	p.FullAddress = val
}
func (p *UserPositionResponse) SetCountry(val string) {
	p.Country = val
}
func (p *UserPositionResponse) SetCountryCode(val string) {
	p.CountryCode = val
}
func (p *UserPositionResponse) SetIsDelete(val int8) {
	p.IsDelete = val
}
func (p *UserPositionResponse) SetCreatedBy(val int64) {
	p.CreatedBy = val
}
func (p *UserPositionResponse) SetUpdatedBy(val int64) {
	p.UpdatedBy = val
}
func (p *UserPositionResponse) SetCreateTime(val int64) {
	p.CreateTime = val
}
func (p *UserPositionResponse) SetUpdateTime(val int64) {
	p.UpdateTime = val
}

func (p *UserPositionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionResponse(%+v)", *p)
}

var fieldIDToName_UserPositionResponse = map[int16]string{
	1:  "id",
	2:  "userId",
	3:  "latitude",
	4:  "longitude",
	5:  "province",
	6:  "city",
	7:  "district",
	8:  "street",
	9:  "fullAddress",
	10: "country",
	11: "countryCode",
	12: "isDelete",
	13: "createdBy",
	14: "updatedBy",
	15: "createTime",
	16: "updateTime",
}

type UserPositionPageResponse struct {
	Total   int64                   `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*UserPositionResponse `thrift:"records,2" frugal:"2,default,list<UserPositionResponse>" json:"records"`
}

func NewUserPositionPageResponse() *UserPositionPageResponse {
	return &UserPositionPageResponse{}
}

func (p *UserPositionPageResponse) InitDefault() {
}

func (p *UserPositionPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *UserPositionPageResponse) GetRecords() (v []*UserPositionResponse) {
	return p.Records
}
func (p *UserPositionPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *UserPositionPageResponse) SetRecords(val []*UserPositionResponse) {
	p.Records = val
}

func (p *UserPositionPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionPageResponse(%+v)", *p)
}

var fieldIDToName_UserPositionPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
