// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user_position

import (
	"fmt"
	"github.com/kouleen/idl/kitex_gen/common"
)

type UserPositionRequest struct {
	UserId      *int64              `thrift:"userId,1,optional" frugal:"1,optional,i64" json:"userId,omitempty"`
	Latitude    *float64            `thrift:"latitude,2,optional" frugal:"2,optional,double" json:"latitude,omitempty"`
	Longitude   *float64            `thrift:"longitude,3,optional" frugal:"3,optional,double" json:"longitude,omitempty"`
	Province    *string             `thrift:"province,4,optional" frugal:"4,optional,string" json:"province,omitempty"`
	City        *string             `thrift:"city,5,optional" frugal:"5,optional,string" json:"city,omitempty"`
	District    *string             `thrift:"district,6,optional" frugal:"6,optional,string" json:"district,omitempty"`
	Street      *string             `thrift:"street,7,optional" frugal:"7,optional,string" json:"street,omitempty"`
	FullAddress *string             `thrift:"fullAddress,8,optional" frugal:"8,optional,string" json:"fullAddress,omitempty"`
	Country     *string             `thrift:"country,9,optional" frugal:"9,optional,string" json:"country,omitempty"`
	CountryCode *string             `thrift:"countryCode,10,optional" frugal:"10,optional,string" json:"countryCode,omitempty"`
	PageRequest *common.PageRequest `thrift:"PageRequest,11,optional" frugal:"11,optional,common.PageRequest" json:"PageRequest,omitempty"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255,optional" frugal:"255,optional,common.BaseRequest" json:"BaseRequest,omitempty"`
}

func NewUserPositionRequest() *UserPositionRequest {
	return &UserPositionRequest{}
}

func (p *UserPositionRequest) InitDefault() {
}

var UserPositionRequest_UserId_DEFAULT int64

func (p *UserPositionRequest) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return UserPositionRequest_UserId_DEFAULT
	}
	return *p.UserId
}

var UserPositionRequest_Latitude_DEFAULT float64

func (p *UserPositionRequest) GetLatitude() (v float64) {
	if !p.IsSetLatitude() {
		return UserPositionRequest_Latitude_DEFAULT
	}
	return *p.Latitude
}

var UserPositionRequest_Longitude_DEFAULT float64

func (p *UserPositionRequest) GetLongitude() (v float64) {
	if !p.IsSetLongitude() {
		return UserPositionRequest_Longitude_DEFAULT
	}
	return *p.Longitude
}

var UserPositionRequest_Province_DEFAULT string

func (p *UserPositionRequest) GetProvince() (v string) {
	if !p.IsSetProvince() {
		return UserPositionRequest_Province_DEFAULT
	}
	return *p.Province
}

var UserPositionRequest_City_DEFAULT string

func (p *UserPositionRequest) GetCity() (v string) {
	if !p.IsSetCity() {
		return UserPositionRequest_City_DEFAULT
	}
	return *p.City
}

var UserPositionRequest_District_DEFAULT string

func (p *UserPositionRequest) GetDistrict() (v string) {
	if !p.IsSetDistrict() {
		return UserPositionRequest_District_DEFAULT
	}
	return *p.District
}

var UserPositionRequest_Street_DEFAULT string

func (p *UserPositionRequest) GetStreet() (v string) {
	if !p.IsSetStreet() {
		return UserPositionRequest_Street_DEFAULT
	}
	return *p.Street
}

var UserPositionRequest_FullAddress_DEFAULT string

func (p *UserPositionRequest) GetFullAddress() (v string) {
	if !p.IsSetFullAddress() {
		return UserPositionRequest_FullAddress_DEFAULT
	}
	return *p.FullAddress
}

var UserPositionRequest_Country_DEFAULT string

func (p *UserPositionRequest) GetCountry() (v string) {
	if !p.IsSetCountry() {
		return UserPositionRequest_Country_DEFAULT
	}
	return *p.Country
}

var UserPositionRequest_CountryCode_DEFAULT string

func (p *UserPositionRequest) GetCountryCode() (v string) {
	if !p.IsSetCountryCode() {
		return UserPositionRequest_CountryCode_DEFAULT
	}
	return *p.CountryCode
}

var UserPositionRequest_PageRequest_DEFAULT *common.PageRequest

func (p *UserPositionRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return UserPositionRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var UserPositionRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *UserPositionRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return UserPositionRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *UserPositionRequest) SetUserId(val *int64) {
	p.UserId = val
}
func (p *UserPositionRequest) SetLatitude(val *float64) {
	p.Latitude = val
}
func (p *UserPositionRequest) SetLongitude(val *float64) {
	p.Longitude = val
}
func (p *UserPositionRequest) SetProvince(val *string) {
	p.Province = val
}
func (p *UserPositionRequest) SetCity(val *string) {
	p.City = val
}
func (p *UserPositionRequest) SetDistrict(val *string) {
	p.District = val
}
func (p *UserPositionRequest) SetStreet(val *string) {
	p.Street = val
}
func (p *UserPositionRequest) SetFullAddress(val *string) {
	p.FullAddress = val
}
func (p *UserPositionRequest) SetCountry(val *string) {
	p.Country = val
}
func (p *UserPositionRequest) SetCountryCode(val *string) {
	p.CountryCode = val
}
func (p *UserPositionRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *UserPositionRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *UserPositionRequest) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *UserPositionRequest) IsSetLatitude() bool {
	return p.Latitude != nil
}

func (p *UserPositionRequest) IsSetLongitude() bool {
	return p.Longitude != nil
}

func (p *UserPositionRequest) IsSetProvince() bool {
	return p.Province != nil
}

func (p *UserPositionRequest) IsSetCity() bool {
	return p.City != nil
}

func (p *UserPositionRequest) IsSetDistrict() bool {
	return p.District != nil
}

func (p *UserPositionRequest) IsSetStreet() bool {
	return p.Street != nil
}

func (p *UserPositionRequest) IsSetFullAddress() bool {
	return p.FullAddress != nil
}

func (p *UserPositionRequest) IsSetCountry() bool {
	return p.Country != nil
}

func (p *UserPositionRequest) IsSetCountryCode() bool {
	return p.CountryCode != nil
}

func (p *UserPositionRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *UserPositionRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *UserPositionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionRequest(%+v)", *p)
}

var fieldIDToName_UserPositionRequest = map[int16]string{
	1:   "userId",
	2:   "latitude",
	3:   "longitude",
	4:   "province",
	5:   "city",
	6:   "district",
	7:   "street",
	8:   "fullAddress",
	9:   "country",
	10:  "countryCode",
	11:  "PageRequest",
	255: "BaseRequest",
}

type UserPositionResponse struct {
	UserId       *int64               `thrift:"userId,1,optional" frugal:"1,optional,i64" json:"userId,omitempty"`
	Latitude     *float64             `thrift:"latitude,2,optional" frugal:"2,optional,double" json:"latitude,omitempty"`
	Longitude    *float64             `thrift:"longitude,3,optional" frugal:"3,optional,double" json:"longitude,omitempty"`
	Province     *string              `thrift:"province,4,optional" frugal:"4,optional,string" json:"province,omitempty"`
	City         *string              `thrift:"city,5,optional" frugal:"5,optional,string" json:"city,omitempty"`
	District     *string              `thrift:"district,6,optional" frugal:"6,optional,string" json:"district,omitempty"`
	Street       *string              `thrift:"street,7,optional" frugal:"7,optional,string" json:"street,omitempty"`
	FullAddress  *string              `thrift:"fullAddress,8,optional" frugal:"8,optional,string" json:"fullAddress,omitempty"`
	Country      *string              `thrift:"country,9,optional" frugal:"9,optional,string" json:"country,omitempty"`
	CountryCode  *string              `thrift:"countryCode,10,optional" frugal:"10,optional,string" json:"countryCode,omitempty"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewUserPositionResponse() *UserPositionResponse {
	return &UserPositionResponse{}
}

func (p *UserPositionResponse) InitDefault() {
}

var UserPositionResponse_UserId_DEFAULT int64

func (p *UserPositionResponse) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return UserPositionResponse_UserId_DEFAULT
	}
	return *p.UserId
}

var UserPositionResponse_Latitude_DEFAULT float64

func (p *UserPositionResponse) GetLatitude() (v float64) {
	if !p.IsSetLatitude() {
		return UserPositionResponse_Latitude_DEFAULT
	}
	return *p.Latitude
}

var UserPositionResponse_Longitude_DEFAULT float64

func (p *UserPositionResponse) GetLongitude() (v float64) {
	if !p.IsSetLongitude() {
		return UserPositionResponse_Longitude_DEFAULT
	}
	return *p.Longitude
}

var UserPositionResponse_Province_DEFAULT string

func (p *UserPositionResponse) GetProvince() (v string) {
	if !p.IsSetProvince() {
		return UserPositionResponse_Province_DEFAULT
	}
	return *p.Province
}

var UserPositionResponse_City_DEFAULT string

func (p *UserPositionResponse) GetCity() (v string) {
	if !p.IsSetCity() {
		return UserPositionResponse_City_DEFAULT
	}
	return *p.City
}

var UserPositionResponse_District_DEFAULT string

func (p *UserPositionResponse) GetDistrict() (v string) {
	if !p.IsSetDistrict() {
		return UserPositionResponse_District_DEFAULT
	}
	return *p.District
}

var UserPositionResponse_Street_DEFAULT string

func (p *UserPositionResponse) GetStreet() (v string) {
	if !p.IsSetStreet() {
		return UserPositionResponse_Street_DEFAULT
	}
	return *p.Street
}

var UserPositionResponse_FullAddress_DEFAULT string

func (p *UserPositionResponse) GetFullAddress() (v string) {
	if !p.IsSetFullAddress() {
		return UserPositionResponse_FullAddress_DEFAULT
	}
	return *p.FullAddress
}

var UserPositionResponse_Country_DEFAULT string

func (p *UserPositionResponse) GetCountry() (v string) {
	if !p.IsSetCountry() {
		return UserPositionResponse_Country_DEFAULT
	}
	return *p.Country
}

var UserPositionResponse_CountryCode_DEFAULT string

func (p *UserPositionResponse) GetCountryCode() (v string) {
	if !p.IsSetCountryCode() {
		return UserPositionResponse_CountryCode_DEFAULT
	}
	return *p.CountryCode
}

var UserPositionResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *UserPositionResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return UserPositionResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *UserPositionResponse) SetUserId(val *int64) {
	p.UserId = val
}
func (p *UserPositionResponse) SetLatitude(val *float64) {
	p.Latitude = val
}
func (p *UserPositionResponse) SetLongitude(val *float64) {
	p.Longitude = val
}
func (p *UserPositionResponse) SetProvince(val *string) {
	p.Province = val
}
func (p *UserPositionResponse) SetCity(val *string) {
	p.City = val
}
func (p *UserPositionResponse) SetDistrict(val *string) {
	p.District = val
}
func (p *UserPositionResponse) SetStreet(val *string) {
	p.Street = val
}
func (p *UserPositionResponse) SetFullAddress(val *string) {
	p.FullAddress = val
}
func (p *UserPositionResponse) SetCountry(val *string) {
	p.Country = val
}
func (p *UserPositionResponse) SetCountryCode(val *string) {
	p.CountryCode = val
}
func (p *UserPositionResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *UserPositionResponse) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *UserPositionResponse) IsSetLatitude() bool {
	return p.Latitude != nil
}

func (p *UserPositionResponse) IsSetLongitude() bool {
	return p.Longitude != nil
}

func (p *UserPositionResponse) IsSetProvince() bool {
	return p.Province != nil
}

func (p *UserPositionResponse) IsSetCity() bool {
	return p.City != nil
}

func (p *UserPositionResponse) IsSetDistrict() bool {
	return p.District != nil
}

func (p *UserPositionResponse) IsSetStreet() bool {
	return p.Street != nil
}

func (p *UserPositionResponse) IsSetFullAddress() bool {
	return p.FullAddress != nil
}

func (p *UserPositionResponse) IsSetCountry() bool {
	return p.Country != nil
}

func (p *UserPositionResponse) IsSetCountryCode() bool {
	return p.CountryCode != nil
}

func (p *UserPositionResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *UserPositionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionResponse(%+v)", *p)
}

var fieldIDToName_UserPositionResponse = map[int16]string{
	1:   "userId",
	2:   "latitude",
	3:   "longitude",
	4:   "province",
	5:   "city",
	6:   "district",
	7:   "street",
	8:   "fullAddress",
	9:   "country",
	10:  "countryCode",
	255: "BaseResponse",
}

type UserPositionPageResponse struct {
	Total   int64                   `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*UserPositionResponse `thrift:"records,2,required" frugal:"2,required,list<UserPositionResponse>" json:"records"`
}

func NewUserPositionPageResponse() *UserPositionPageResponse {
	return &UserPositionPageResponse{}
}

func (p *UserPositionPageResponse) InitDefault() {
}

func (p *UserPositionPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *UserPositionPageResponse) GetRecords() (v []*UserPositionResponse) {
	return p.Records
}
func (p *UserPositionPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *UserPositionPageResponse) SetRecords(val []*UserPositionResponse) {
	p.Records = val
}

func (p *UserPositionPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionPageResponse(%+v)", *p)
}

var fieldIDToName_UserPositionPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
