// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user_position

import (
	"fmt"
	"github.com/kouleen/idl/kitex_gen/common"
)

type UserPositionRequest struct {
	UserId      *int64              `thrift:"userId,1,optional" frugal:"1,optional,i64" json:"userId,omitempty"`
	Latitude    *float64            `thrift:"latitude,2,optional" frugal:"2,optional,double" json:"latitude,omitempty"`
	Longitude   *float64            `thrift:"longitude,3,optional" frugal:"3,optional,double" json:"longitude,omitempty"`
	Province    string              `thrift:"province,4" frugal:"4,default,string" json:"province"`
	City        string              `thrift:"city,5" frugal:"5,default,string" json:"city"`
	District    string              `thrift:"district,6" frugal:"6,default,string" json:"district"`
	Street      string              `thrift:"street,7" frugal:"7,default,string" json:"street"`
	FullAddress string              `thrift:"fullAddress,8" frugal:"8,default,string" json:"fullAddress"`
	Country     string              `thrift:"country,9" frugal:"9,default,string" json:"country"`
	CountryCode string              `thrift:"countryCode,10" frugal:"10,default,string" json:"countryCode"`
	PageRequest *common.PageRequest `thrift:"PageRequest,11" frugal:"11,default,common.PageRequest" json:"PageRequest"`
	BaseRequest *common.BaseRequest `thrift:"BaseRequest,255" frugal:"255,default,common.BaseRequest" json:"BaseRequest"`
}

func NewUserPositionRequest() *UserPositionRequest {
	return &UserPositionRequest{}
}

func (p *UserPositionRequest) InitDefault() {
}

var UserPositionRequest_UserId_DEFAULT int64

func (p *UserPositionRequest) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return UserPositionRequest_UserId_DEFAULT
	}
	return *p.UserId
}

var UserPositionRequest_Latitude_DEFAULT float64

func (p *UserPositionRequest) GetLatitude() (v float64) {
	if !p.IsSetLatitude() {
		return UserPositionRequest_Latitude_DEFAULT
	}
	return *p.Latitude
}

var UserPositionRequest_Longitude_DEFAULT float64

func (p *UserPositionRequest) GetLongitude() (v float64) {
	if !p.IsSetLongitude() {
		return UserPositionRequest_Longitude_DEFAULT
	}
	return *p.Longitude
}

func (p *UserPositionRequest) GetProvince() (v string) {
	return p.Province
}

func (p *UserPositionRequest) GetCity() (v string) {
	return p.City
}

func (p *UserPositionRequest) GetDistrict() (v string) {
	return p.District
}

func (p *UserPositionRequest) GetStreet() (v string) {
	return p.Street
}

func (p *UserPositionRequest) GetFullAddress() (v string) {
	return p.FullAddress
}

func (p *UserPositionRequest) GetCountry() (v string) {
	return p.Country
}

func (p *UserPositionRequest) GetCountryCode() (v string) {
	return p.CountryCode
}

var UserPositionRequest_PageRequest_DEFAULT *common.PageRequest

func (p *UserPositionRequest) GetPageRequest() (v *common.PageRequest) {
	if !p.IsSetPageRequest() {
		return UserPositionRequest_PageRequest_DEFAULT
	}
	return p.PageRequest
}

var UserPositionRequest_BaseRequest_DEFAULT *common.BaseRequest

func (p *UserPositionRequest) GetBaseRequest() (v *common.BaseRequest) {
	if !p.IsSetBaseRequest() {
		return UserPositionRequest_BaseRequest_DEFAULT
	}
	return p.BaseRequest
}
func (p *UserPositionRequest) SetUserId(val *int64) {
	p.UserId = val
}
func (p *UserPositionRequest) SetLatitude(val *float64) {
	p.Latitude = val
}
func (p *UserPositionRequest) SetLongitude(val *float64) {
	p.Longitude = val
}
func (p *UserPositionRequest) SetProvince(val string) {
	p.Province = val
}
func (p *UserPositionRequest) SetCity(val string) {
	p.City = val
}
func (p *UserPositionRequest) SetDistrict(val string) {
	p.District = val
}
func (p *UserPositionRequest) SetStreet(val string) {
	p.Street = val
}
func (p *UserPositionRequest) SetFullAddress(val string) {
	p.FullAddress = val
}
func (p *UserPositionRequest) SetCountry(val string) {
	p.Country = val
}
func (p *UserPositionRequest) SetCountryCode(val string) {
	p.CountryCode = val
}
func (p *UserPositionRequest) SetPageRequest(val *common.PageRequest) {
	p.PageRequest = val
}
func (p *UserPositionRequest) SetBaseRequest(val *common.BaseRequest) {
	p.BaseRequest = val
}

func (p *UserPositionRequest) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *UserPositionRequest) IsSetLatitude() bool {
	return p.Latitude != nil
}

func (p *UserPositionRequest) IsSetLongitude() bool {
	return p.Longitude != nil
}

func (p *UserPositionRequest) IsSetPageRequest() bool {
	return p.PageRequest != nil
}

func (p *UserPositionRequest) IsSetBaseRequest() bool {
	return p.BaseRequest != nil
}

func (p *UserPositionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionRequest(%+v)", *p)
}

var fieldIDToName_UserPositionRequest = map[int16]string{
	1:   "userId",
	2:   "latitude",
	3:   "longitude",
	4:   "province",
	5:   "city",
	6:   "district",
	7:   "street",
	8:   "fullAddress",
	9:   "country",
	10:  "countryCode",
	11:  "PageRequest",
	255: "BaseRequest",
}

type UserPositionResponse struct {
	UserId       int64                `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Latitude     float64              `thrift:"latitude,2" frugal:"2,default,double" json:"latitude"`
	Longitude    float64              `thrift:"longitude,3" frugal:"3,default,double" json:"longitude"`
	Province     string               `thrift:"province,4" frugal:"4,default,string" json:"province"`
	City         string               `thrift:"city,5" frugal:"5,default,string" json:"city"`
	District     string               `thrift:"district,6" frugal:"6,default,string" json:"district"`
	Street       string               `thrift:"street,7" frugal:"7,default,string" json:"street"`
	FullAddress  string               `thrift:"fullAddress,8" frugal:"8,default,string" json:"fullAddress"`
	Country      string               `thrift:"country,9" frugal:"9,default,string" json:"country"`
	CountryCode  string               `thrift:"countryCode,10" frugal:"10,default,string" json:"countryCode"`
	BaseResponse *common.BaseResponse `thrift:"BaseResponse,255" frugal:"255,default,common.BaseResponse" json:"BaseResponse"`
}

func NewUserPositionResponse() *UserPositionResponse {
	return &UserPositionResponse{}
}

func (p *UserPositionResponse) InitDefault() {
}

func (p *UserPositionResponse) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserPositionResponse) GetLatitude() (v float64) {
	return p.Latitude
}

func (p *UserPositionResponse) GetLongitude() (v float64) {
	return p.Longitude
}

func (p *UserPositionResponse) GetProvince() (v string) {
	return p.Province
}

func (p *UserPositionResponse) GetCity() (v string) {
	return p.City
}

func (p *UserPositionResponse) GetDistrict() (v string) {
	return p.District
}

func (p *UserPositionResponse) GetStreet() (v string) {
	return p.Street
}

func (p *UserPositionResponse) GetFullAddress() (v string) {
	return p.FullAddress
}

func (p *UserPositionResponse) GetCountry() (v string) {
	return p.Country
}

func (p *UserPositionResponse) GetCountryCode() (v string) {
	return p.CountryCode
}

var UserPositionResponse_BaseResponse_DEFAULT *common.BaseResponse

func (p *UserPositionResponse) GetBaseResponse() (v *common.BaseResponse) {
	if !p.IsSetBaseResponse() {
		return UserPositionResponse_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}
func (p *UserPositionResponse) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserPositionResponse) SetLatitude(val float64) {
	p.Latitude = val
}
func (p *UserPositionResponse) SetLongitude(val float64) {
	p.Longitude = val
}
func (p *UserPositionResponse) SetProvince(val string) {
	p.Province = val
}
func (p *UserPositionResponse) SetCity(val string) {
	p.City = val
}
func (p *UserPositionResponse) SetDistrict(val string) {
	p.District = val
}
func (p *UserPositionResponse) SetStreet(val string) {
	p.Street = val
}
func (p *UserPositionResponse) SetFullAddress(val string) {
	p.FullAddress = val
}
func (p *UserPositionResponse) SetCountry(val string) {
	p.Country = val
}
func (p *UserPositionResponse) SetCountryCode(val string) {
	p.CountryCode = val
}
func (p *UserPositionResponse) SetBaseResponse(val *common.BaseResponse) {
	p.BaseResponse = val
}

func (p *UserPositionResponse) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *UserPositionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionResponse(%+v)", *p)
}

var fieldIDToName_UserPositionResponse = map[int16]string{
	1:   "userId",
	2:   "latitude",
	3:   "longitude",
	4:   "province",
	5:   "city",
	6:   "district",
	7:   "street",
	8:   "fullAddress",
	9:   "country",
	10:  "countryCode",
	255: "BaseResponse",
}

type UserPositionPageResponse struct {
	Total   int64                   `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Records []*UserPositionResponse `thrift:"records,2" frugal:"2,default,list<UserPositionResponse>" json:"records"`
}

func NewUserPositionPageResponse() *UserPositionPageResponse {
	return &UserPositionPageResponse{}
}

func (p *UserPositionPageResponse) InitDefault() {
}

func (p *UserPositionPageResponse) GetTotal() (v int64) {
	return p.Total
}

func (p *UserPositionPageResponse) GetRecords() (v []*UserPositionResponse) {
	return p.Records
}
func (p *UserPositionPageResponse) SetTotal(val int64) {
	p.Total = val
}
func (p *UserPositionPageResponse) SetRecords(val []*UserPositionResponse) {
	p.Records = val
}

func (p *UserPositionPageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserPositionPageResponse(%+v)", *p)
}

var fieldIDToName_UserPositionPageResponse = map[int16]string{
	1: "total",
	2: "records",
}
