// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type BaseStatus int64

const (
	BaseStatus_DISABLED BaseStatus = 0
	BaseStatus_ENABLE   BaseStatus = 1
)

func (p BaseStatus) String() string {
	switch p {
	case BaseStatus_DISABLED:
		return "DISABLED"
	case BaseStatus_ENABLE:
		return "ENABLE"
	}
	return "<UNSET>"
}

func BaseStatusFromString(s string) (BaseStatus, error) {
	switch s {
	case "DISABLED":
		return BaseStatus_DISABLED, nil
	case "ENABLE":
		return BaseStatus_ENABLE, nil
	}
	return BaseStatus(0), fmt.Errorf("not a valid BaseStatus string")
}

func BaseStatusPtr(v BaseStatus) *BaseStatus { return &v }
func (p *BaseStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = BaseStatus(result.Int64)
	return
}

func (p *BaseStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
