// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package common

import (
	"fmt"
)

type BaseQueryRequest struct {
	BeginTime string `thrift:"beginTime,1" frugal:"1,default,string" json:"beginTime"`
	EndTime   string `thrift:"endTime,2" frugal:"2,default,string" json:"endTime"`
}

func NewBaseQueryRequest() *BaseQueryRequest {
	return &BaseQueryRequest{}
}

func (p *BaseQueryRequest) InitDefault() {
}

func (p *BaseQueryRequest) GetBeginTime() (v string) {
	return p.BeginTime
}

func (p *BaseQueryRequest) GetEndTime() (v string) {
	return p.EndTime
}
func (p *BaseQueryRequest) SetBeginTime(val string) {
	p.BeginTime = val
}
func (p *BaseQueryRequest) SetEndTime(val string) {
	p.EndTime = val
}

func (p *BaseQueryRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseQueryRequest(%+v)", *p)
}

var fieldIDToName_BaseQueryRequest = map[int16]string{
	1: "beginTime",
	2: "endTime",
}
