// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"github.com/kouleen/idl/kitex_gen/user_position"
)

type UserService interface {
	Captcha(ctx context.Context, req *LoginRequest) (r bool, err error)

	SmsCode(ctx context.Context, phone string) (r bool, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	Register(ctx context.Context, req *RegisterRequest) (r bool, err error)

	ResetPwd(ctx context.Context, req *LoginRequest) (r bool, err error)

	Logout(ctx context.Context, req *LoginRequest) (r bool, err error)

	QueryUserHeaderPage(ctx context.Context, req *UserHeaderRequest) (r *UserHeaderPageResponse, err error)

	QueryUserHeaderList(ctx context.Context, req *UserHeaderRequest) (r []*UserHeaderResponse, err error)

	QueryUserHeaderInfo(ctx context.Context, req *UserHeaderRequest) (r *UserHeaderResponse, err error)

	QueryUserPositionPage(ctx context.Context, req *user_position.UserPositionRequest) (r *user_position.UserPositionPageResponse, err error)

	SaveUserPosition(ctx context.Context, req *user_position.UserPositionRequest) (r bool, err error)

	UpdateUserPosition(ctx context.Context, req *user_position.UserPositionRequest) (r bool, err error)

	DeleteUserPosition(ctx context.Context, req *user_position.UserPositionRequest) (r bool, err error)
}

type UserServiceCaptchaArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceCaptchaArgs() *UserServiceCaptchaArgs {
	return &UserServiceCaptchaArgs{}
}

func (p *UserServiceCaptchaArgs) InitDefault() {
}

var UserServiceCaptchaArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceCaptchaArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceCaptchaArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceCaptchaArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceCaptchaArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceCaptchaArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCaptchaArgs(%+v)", *p)
}

var fieldIDToName_UserServiceCaptchaArgs = map[int16]string{
	1: "req",
}

type UserServiceCaptchaResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceCaptchaResult() *UserServiceCaptchaResult {
	return &UserServiceCaptchaResult{}
}

func (p *UserServiceCaptchaResult) InitDefault() {
}

var UserServiceCaptchaResult_Success_DEFAULT bool

func (p *UserServiceCaptchaResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceCaptchaResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceCaptchaResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceCaptchaResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceCaptchaResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceCaptchaResult(%+v)", *p)
}

var fieldIDToName_UserServiceCaptchaResult = map[int16]string{
	0: "success",
}

type UserServiceSmsCodeArgs struct {
	Phone string `thrift:"phone,1" frugal:"1,default,string" json:"phone"`
}

func NewUserServiceSmsCodeArgs() *UserServiceSmsCodeArgs {
	return &UserServiceSmsCodeArgs{}
}

func (p *UserServiceSmsCodeArgs) InitDefault() {
}

func (p *UserServiceSmsCodeArgs) GetPhone() (v string) {
	return p.Phone
}
func (p *UserServiceSmsCodeArgs) SetPhone(val string) {
	p.Phone = val
}

func (p *UserServiceSmsCodeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSmsCodeArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSmsCodeArgs = map[int16]string{
	1: "phone",
}

type UserServiceSmsCodeResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceSmsCodeResult() *UserServiceSmsCodeResult {
	return &UserServiceSmsCodeResult{}
}

func (p *UserServiceSmsCodeResult) InitDefault() {
}

var UserServiceSmsCodeResult_Success_DEFAULT bool

func (p *UserServiceSmsCodeResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceSmsCodeResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceSmsCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceSmsCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSmsCodeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSmsCodeResult(%+v)", *p)
}

var fieldIDToName_UserServiceSmsCodeResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT bool

func (p *UserServiceRegisterResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceResetPwdArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceResetPwdArgs() *UserServiceResetPwdArgs {
	return &UserServiceResetPwdArgs{}
}

func (p *UserServiceResetPwdArgs) InitDefault() {
}

var UserServiceResetPwdArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceResetPwdArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceResetPwdArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceResetPwdArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceResetPwdArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceResetPwdArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPwdArgs(%+v)", *p)
}

var fieldIDToName_UserServiceResetPwdArgs = map[int16]string{
	1: "req",
}

type UserServiceResetPwdResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceResetPwdResult() *UserServiceResetPwdResult {
	return &UserServiceResetPwdResult{}
}

func (p *UserServiceResetPwdResult) InitDefault() {
}

var UserServiceResetPwdResult_Success_DEFAULT bool

func (p *UserServiceResetPwdResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceResetPwdResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceResetPwdResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceResetPwdResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceResetPwdResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceResetPwdResult(%+v)", *p)
}

var fieldIDToName_UserServiceResetPwdResult = map[int16]string{
	0: "success",
}

type UserServiceLogoutArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceLogoutArgs() *UserServiceLogoutArgs {
	return &UserServiceLogoutArgs{}
}

func (p *UserServiceLogoutArgs) InitDefault() {
}

var UserServiceLogoutArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceLogoutArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLogoutArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutArgs = map[int16]string{
	1: "req",
}

type UserServiceLogoutResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceLogoutResult() *UserServiceLogoutResult {
	return &UserServiceLogoutResult{}
}

func (p *UserServiceLogoutResult) InitDefault() {
}

var UserServiceLogoutResult_Success_DEFAULT bool

func (p *UserServiceLogoutResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceLogoutResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutResult = map[int16]string{
	0: "success",
}

type UserServiceQueryUserHeaderPageArgs struct {
	Req *UserHeaderRequest `thrift:"req,1" frugal:"1,default,UserHeaderRequest" json:"req"`
}

func NewUserServiceQueryUserHeaderPageArgs() *UserServiceQueryUserHeaderPageArgs {
	return &UserServiceQueryUserHeaderPageArgs{}
}

func (p *UserServiceQueryUserHeaderPageArgs) InitDefault() {
}

var UserServiceQueryUserHeaderPageArgs_Req_DEFAULT *UserHeaderRequest

func (p *UserServiceQueryUserHeaderPageArgs) GetReq() (v *UserHeaderRequest) {
	if !p.IsSetReq() {
		return UserServiceQueryUserHeaderPageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceQueryUserHeaderPageArgs) SetReq(val *UserHeaderRequest) {
	p.Req = val
}

func (p *UserServiceQueryUserHeaderPageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceQueryUserHeaderPageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserHeaderPageArgs(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserHeaderPageArgs = map[int16]string{
	1: "req",
}

type UserServiceQueryUserHeaderPageResult struct {
	Success *UserHeaderPageResponse `thrift:"success,0,optional" frugal:"0,optional,UserHeaderPageResponse" json:"success,omitempty"`
}

func NewUserServiceQueryUserHeaderPageResult() *UserServiceQueryUserHeaderPageResult {
	return &UserServiceQueryUserHeaderPageResult{}
}

func (p *UserServiceQueryUserHeaderPageResult) InitDefault() {
}

var UserServiceQueryUserHeaderPageResult_Success_DEFAULT *UserHeaderPageResponse

func (p *UserServiceQueryUserHeaderPageResult) GetSuccess() (v *UserHeaderPageResponse) {
	if !p.IsSetSuccess() {
		return UserServiceQueryUserHeaderPageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceQueryUserHeaderPageResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserHeaderPageResponse)
}

func (p *UserServiceQueryUserHeaderPageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceQueryUserHeaderPageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserHeaderPageResult(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserHeaderPageResult = map[int16]string{
	0: "success",
}

type UserServiceQueryUserHeaderListArgs struct {
	Req *UserHeaderRequest `thrift:"req,1" frugal:"1,default,UserHeaderRequest" json:"req"`
}

func NewUserServiceQueryUserHeaderListArgs() *UserServiceQueryUserHeaderListArgs {
	return &UserServiceQueryUserHeaderListArgs{}
}

func (p *UserServiceQueryUserHeaderListArgs) InitDefault() {
}

var UserServiceQueryUserHeaderListArgs_Req_DEFAULT *UserHeaderRequest

func (p *UserServiceQueryUserHeaderListArgs) GetReq() (v *UserHeaderRequest) {
	if !p.IsSetReq() {
		return UserServiceQueryUserHeaderListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceQueryUserHeaderListArgs) SetReq(val *UserHeaderRequest) {
	p.Req = val
}

func (p *UserServiceQueryUserHeaderListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceQueryUserHeaderListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserHeaderListArgs(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserHeaderListArgs = map[int16]string{
	1: "req",
}

type UserServiceQueryUserHeaderListResult struct {
	Success []*UserHeaderResponse `thrift:"success,0,optional" frugal:"0,optional,list<UserHeaderResponse>" json:"success,omitempty"`
}

func NewUserServiceQueryUserHeaderListResult() *UserServiceQueryUserHeaderListResult {
	return &UserServiceQueryUserHeaderListResult{}
}

func (p *UserServiceQueryUserHeaderListResult) InitDefault() {
}

var UserServiceQueryUserHeaderListResult_Success_DEFAULT []*UserHeaderResponse

func (p *UserServiceQueryUserHeaderListResult) GetSuccess() (v []*UserHeaderResponse) {
	if !p.IsSetSuccess() {
		return UserServiceQueryUserHeaderListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceQueryUserHeaderListResult) SetSuccess(x interface{}) {
	p.Success = x.([]*UserHeaderResponse)
}

func (p *UserServiceQueryUserHeaderListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceQueryUserHeaderListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserHeaderListResult(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserHeaderListResult = map[int16]string{
	0: "success",
}

type UserServiceQueryUserHeaderInfoArgs struct {
	Req *UserHeaderRequest `thrift:"req,1" frugal:"1,default,UserHeaderRequest" json:"req"`
}

func NewUserServiceQueryUserHeaderInfoArgs() *UserServiceQueryUserHeaderInfoArgs {
	return &UserServiceQueryUserHeaderInfoArgs{}
}

func (p *UserServiceQueryUserHeaderInfoArgs) InitDefault() {
}

var UserServiceQueryUserHeaderInfoArgs_Req_DEFAULT *UserHeaderRequest

func (p *UserServiceQueryUserHeaderInfoArgs) GetReq() (v *UserHeaderRequest) {
	if !p.IsSetReq() {
		return UserServiceQueryUserHeaderInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceQueryUserHeaderInfoArgs) SetReq(val *UserHeaderRequest) {
	p.Req = val
}

func (p *UserServiceQueryUserHeaderInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceQueryUserHeaderInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserHeaderInfoArgs(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserHeaderInfoArgs = map[int16]string{
	1: "req",
}

type UserServiceQueryUserHeaderInfoResult struct {
	Success *UserHeaderResponse `thrift:"success,0,optional" frugal:"0,optional,UserHeaderResponse" json:"success,omitempty"`
}

func NewUserServiceQueryUserHeaderInfoResult() *UserServiceQueryUserHeaderInfoResult {
	return &UserServiceQueryUserHeaderInfoResult{}
}

func (p *UserServiceQueryUserHeaderInfoResult) InitDefault() {
}

var UserServiceQueryUserHeaderInfoResult_Success_DEFAULT *UserHeaderResponse

func (p *UserServiceQueryUserHeaderInfoResult) GetSuccess() (v *UserHeaderResponse) {
	if !p.IsSetSuccess() {
		return UserServiceQueryUserHeaderInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceQueryUserHeaderInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserHeaderResponse)
}

func (p *UserServiceQueryUserHeaderInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceQueryUserHeaderInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserHeaderInfoResult(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserHeaderInfoResult = map[int16]string{
	0: "success",
}

type UserServiceQueryUserPositionPageArgs struct {
	Req *user_position.UserPositionRequest `thrift:"req,1" frugal:"1,default,user_position.UserPositionRequest" json:"req"`
}

func NewUserServiceQueryUserPositionPageArgs() *UserServiceQueryUserPositionPageArgs {
	return &UserServiceQueryUserPositionPageArgs{}
}

func (p *UserServiceQueryUserPositionPageArgs) InitDefault() {
}

var UserServiceQueryUserPositionPageArgs_Req_DEFAULT *user_position.UserPositionRequest

func (p *UserServiceQueryUserPositionPageArgs) GetReq() (v *user_position.UserPositionRequest) {
	if !p.IsSetReq() {
		return UserServiceQueryUserPositionPageArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceQueryUserPositionPageArgs) SetReq(val *user_position.UserPositionRequest) {
	p.Req = val
}

func (p *UserServiceQueryUserPositionPageArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceQueryUserPositionPageArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserPositionPageArgs(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserPositionPageArgs = map[int16]string{
	1: "req",
}

type UserServiceQueryUserPositionPageResult struct {
	Success *user_position.UserPositionPageResponse `thrift:"success,0,optional" frugal:"0,optional,user_position.UserPositionPageResponse" json:"success,omitempty"`
}

func NewUserServiceQueryUserPositionPageResult() *UserServiceQueryUserPositionPageResult {
	return &UserServiceQueryUserPositionPageResult{}
}

func (p *UserServiceQueryUserPositionPageResult) InitDefault() {
}

var UserServiceQueryUserPositionPageResult_Success_DEFAULT *user_position.UserPositionPageResponse

func (p *UserServiceQueryUserPositionPageResult) GetSuccess() (v *user_position.UserPositionPageResponse) {
	if !p.IsSetSuccess() {
		return UserServiceQueryUserPositionPageResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceQueryUserPositionPageResult) SetSuccess(x interface{}) {
	p.Success = x.(*user_position.UserPositionPageResponse)
}

func (p *UserServiceQueryUserPositionPageResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceQueryUserPositionPageResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceQueryUserPositionPageResult(%+v)", *p)
}

var fieldIDToName_UserServiceQueryUserPositionPageResult = map[int16]string{
	0: "success",
}

type UserServiceSaveUserPositionArgs struct {
	Req *user_position.UserPositionRequest `thrift:"req,1" frugal:"1,default,user_position.UserPositionRequest" json:"req"`
}

func NewUserServiceSaveUserPositionArgs() *UserServiceSaveUserPositionArgs {
	return &UserServiceSaveUserPositionArgs{}
}

func (p *UserServiceSaveUserPositionArgs) InitDefault() {
}

var UserServiceSaveUserPositionArgs_Req_DEFAULT *user_position.UserPositionRequest

func (p *UserServiceSaveUserPositionArgs) GetReq() (v *user_position.UserPositionRequest) {
	if !p.IsSetReq() {
		return UserServiceSaveUserPositionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceSaveUserPositionArgs) SetReq(val *user_position.UserPositionRequest) {
	p.Req = val
}

func (p *UserServiceSaveUserPositionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceSaveUserPositionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSaveUserPositionArgs(%+v)", *p)
}

var fieldIDToName_UserServiceSaveUserPositionArgs = map[int16]string{
	1: "req",
}

type UserServiceSaveUserPositionResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceSaveUserPositionResult() *UserServiceSaveUserPositionResult {
	return &UserServiceSaveUserPositionResult{}
}

func (p *UserServiceSaveUserPositionResult) InitDefault() {
}

var UserServiceSaveUserPositionResult_Success_DEFAULT bool

func (p *UserServiceSaveUserPositionResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceSaveUserPositionResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceSaveUserPositionResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceSaveUserPositionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceSaveUserPositionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceSaveUserPositionResult(%+v)", *p)
}

var fieldIDToName_UserServiceSaveUserPositionResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserPositionArgs struct {
	Req *user_position.UserPositionRequest `thrift:"req,1" frugal:"1,default,user_position.UserPositionRequest" json:"req"`
}

func NewUserServiceUpdateUserPositionArgs() *UserServiceUpdateUserPositionArgs {
	return &UserServiceUpdateUserPositionArgs{}
}

func (p *UserServiceUpdateUserPositionArgs) InitDefault() {
}

var UserServiceUpdateUserPositionArgs_Req_DEFAULT *user_position.UserPositionRequest

func (p *UserServiceUpdateUserPositionArgs) GetReq() (v *user_position.UserPositionRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserPositionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserPositionArgs) SetReq(val *user_position.UserPositionRequest) {
	p.Req = val
}

func (p *UserServiceUpdateUserPositionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserPositionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserPositionArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserPositionArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserPositionResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceUpdateUserPositionResult() *UserServiceUpdateUserPositionResult {
	return &UserServiceUpdateUserPositionResult{}
}

func (p *UserServiceUpdateUserPositionResult) InitDefault() {
}

var UserServiceUpdateUserPositionResult_Success_DEFAULT bool

func (p *UserServiceUpdateUserPositionResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserPositionResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceUpdateUserPositionResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceUpdateUserPositionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserPositionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserPositionResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserPositionResult = map[int16]string{
	0: "success",
}

type UserServiceDeleteUserPositionArgs struct {
	Req *user_position.UserPositionRequest `thrift:"req,1" frugal:"1,default,user_position.UserPositionRequest" json:"req"`
}

func NewUserServiceDeleteUserPositionArgs() *UserServiceDeleteUserPositionArgs {
	return &UserServiceDeleteUserPositionArgs{}
}

func (p *UserServiceDeleteUserPositionArgs) InitDefault() {
}

var UserServiceDeleteUserPositionArgs_Req_DEFAULT *user_position.UserPositionRequest

func (p *UserServiceDeleteUserPositionArgs) GetReq() (v *user_position.UserPositionRequest) {
	if !p.IsSetReq() {
		return UserServiceDeleteUserPositionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceDeleteUserPositionArgs) SetReq(val *user_position.UserPositionRequest) {
	p.Req = val
}

func (p *UserServiceDeleteUserPositionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceDeleteUserPositionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserPositionArgs(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserPositionArgs = map[int16]string{
	1: "req",
}

type UserServiceDeleteUserPositionResult struct {
	Success *bool `thrift:"success,0,optional" frugal:"0,optional,bool" json:"success,omitempty"`
}

func NewUserServiceDeleteUserPositionResult() *UserServiceDeleteUserPositionResult {
	return &UserServiceDeleteUserPositionResult{}
}

func (p *UserServiceDeleteUserPositionResult) InitDefault() {
}

var UserServiceDeleteUserPositionResult_Success_DEFAULT bool

func (p *UserServiceDeleteUserPositionResult) GetSuccess() (v bool) {
	if !p.IsSetSuccess() {
		return UserServiceDeleteUserPositionResult_Success_DEFAULT
	}
	return *p.Success
}
func (p *UserServiceDeleteUserPositionResult) SetSuccess(x interface{}) {
	p.Success = x.(*bool)
}

func (p *UserServiceDeleteUserPositionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceDeleteUserPositionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceDeleteUserPositionResult(%+v)", *p)
}

var fieldIDToName_UserServiceDeleteUserPositionResult = map[int16]string{
	0: "success",
}
